import { USER_CAPABILITY_IDS, type ScientificCapability, type UserCapabilityId } from "./types.ts";

function mag(partial: ScientificCapability): ScientificCapability {
  return partial;
}

const CAPABILITIES: ScientificCapability[] = [
  mag({
    id: "mag.diurnal",
    version: "1.0.0",
    title: "Diurnal correction",
    description: "Correct MagArrow rover samples with a GSM-19 base station.",
    domain: "magnetics",
    kernelNodeIds: [
      "file_discovery",
      "flight_path_cleaner",
      "time_synchronizer",
      "diurnal_corrector",
      "qc_engine",
    ],
    dependsOn: [],
    inputRoles: [
      {
        role: "rover",
        adapterIds: ["magarrow"],
        required: true,
        description: "Supported MagArrow airborne catalog records",
      },
      {
        role: "base",
        adapterIds: ["gsm19"],
        required: true,
        description: "Supported GSM-19 base-station catalog records",
      },
    ],
    outputs: [
      { id: "airborne_corrected", type: "table", description: "Diurnally corrected MagArrow samples", viewer: "table" },
      { id: "qc_report", type: "qc", description: "Diurnal QC statistics", viewer: "json" },
    ],
    parameters: {
      baseReference: {
        type: "string",
        required: true,
        description: "GSM-19 reference: mean_base, median_base, or first_sample",
        defaultValue: "mean_base",
      },
      surveyDate: { type: "string", required: false, description: "Survey date YYYY-MM-DD if GSM-19 header has no /ID stamp" },
    },
    metadataRequirements: ["rover timestamps", "base timestamps", "magnetic field nT"],
    scientificConstraints: [
      "Requires both MagArrow rover and GSM-19 base catalog records.",
      "Does not invent a survey date if the GSM-19 header has none.",
    ],
    qcRequirements: ["temporal overlap", "outlier report", "reference value recorded"],
    viewerTypes: ["table", "json"],
    interpretationLimits: [
      "Diurnal correction removes base-station variation only. It is not IGRF, levelling, or RTP.",
    ],
    expectedArtifacts: ["airborne_corrected.csv", "base_station_canonical.csv", "qc_report.json"],
  }),
  mag({
    id: "mag.igrf",
    version: "1.0.0",
    title: "IGRF removal",
    description: "Subtract IGRF-13 at each sample.",
    domain: "magnetics",
    kernelNodeIds: ["igrf_corrector"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Diurnally corrected points" }],
    outputs: [
      { id: "igrf_residual", type: "table", description: "IGRF residual nT plus I/D", viewer: "table" },
      { id: "igrf_qc", type: "qc", description: "Mean inclination/declination", viewer: "json" },
    ],
    parameters: {
      decimalYear: { type: "number", required: false, description: "Override survey decimal year" },
      surveyAltitudeM: { type: "number", required: false, description: "Default altitude when z is missing", units: "m" },
    },
    metadataRequirements: ["geodetic lat/lon", "timestamp or decimalYear"],
    scientificConstraints: ["IGRF-13 official SV window is 2020.0–2025.0; outside that range SV is extrapolated."],
    qcRequirements: ["mean I and D written", "extrapolation flag"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Residual is not RTP. Do not interpret uncorrected TMI as crustal anomaly after this step alone."],
    expectedArtifacts: ["airborne_igrf.csv", "igrf_qc.json"],
  }),
  mag({
    id: "mag.headingLag",
    version: "1.0.0",
    title: "Heading and lag",
    description: "Heading correction and reciprocal-line lag.",
    domain: "magnetics",
    kernelNodeIds: ["heading_lag_corrector"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Corrected MagArrow points" }],
    outputs: [{ id: "heading_lag", type: "table", description: "Heading/lag corrected samples", viewer: "table" }],
    parameters: {},
    metadataRequirements: ["track coordinates", "line structure for lag"],
    scientificConstraints: ["Lag is applied only when reciprocal lines support an estimate."],
    qcRequirements: ["heading RMS", "lag samples or reason not applied"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Does not replace tie-line levelling."],
    expectedArtifacts: ["airborne_heading_lag.csv", "heading_lag_qc.json"],
  }),
  mag({
    id: "mag.level",
    version: "1.0.0",
    title: "Tie-line levelling",
    description: "Statistical levelling of traverses against ties, then microlevelling.",
    domain: "magnetics",
    kernelNodeIds: ["tie_line_leveler", "microleveller"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Corrected MagArrow points" }],
    outputs: [{ id: "leveled", type: "table", description: "Levelled samples", viewer: "table" }],
    parameters: {
      tieRadiusM: { type: "number", required: false, description: "Tie intersection radius", units: "m", defaultValue: 25 },
    },
    metadataRequirements: ["line_id or geometry that distinguishes ties from traverses"],
    scientificConstraints: ["Ties are held; traverses shift. Requires identifiable tie/traverse structure."],
    qcRequirements: ["shift statistics", "microlevel applied flag"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Levelling can suppress geologic signal along-line if mis-parameterised."],
    expectedArtifacts: ["airborne_leveled.csv", "airborne_microleveled.csv", "leveling_qc.json"],
  }),
  mag({
    id: "mag.grid",
    version: "1.0.0",
    title: "Minimum-curvature grid",
    description: "Grid diurnally corrected spatial samples.",
    domain: "magnetics",
    kernelNodeIds: ["mag_gridder"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Corrected MagArrow points with x/y" }],
    outputs: [{ id: "tmi_grid", type: "grid", description: "TMI residual grid", viewer: "map" }],
    parameters: {
      cellSizeM: { type: "number", required: false, description: "Grid cell size", units: "m" },
      gridTension: { type: "number", required: false, description: "Spline tension", defaultValue: 0.25 },
    },
    metadataRequirements: ["spatial x/y", "corrected magnetic values"],
    scientificConstraints: ["Requires diurnally corrected spatial data. Does not grid raw unsupported tables."],
    qcRequirements: ["crs_epsg", "cell size", "grid dimensions"],
    viewerTypes: ["map", "ascii-grid"],
    interpretationLimits: ["Gridding interpolates; it is not a measurement. Cell size must be justified by line spacing."],
    expectedArtifacts: ["tmi_grid.asc", "tmi_grid.npz", "grid_qc.json"],
  }),
  mag({
    id: "mag.rtp",
    version: "1.0.0",
    title: "Reduction to the pole",
    description: "FFT RTP of a TMI grid using inclination and declination.",
    domain: "magnetics",
    kernelNodeIds: ["rtp_filter"],
    dependsOn: ["mag.grid"],
    inputRoles: [{ role: "grid", adapterIds: ["magarrow"], required: true, description: "TMI grid from mag.grid" }],
    outputs: [{ id: "rtp_grid", type: "grid", description: "RTP or documented RTE fallback", viewer: "map" }],
    parameters: {
      inclination: { type: "number", required: false, description: "Magnetic inclination", units: "degrees" },
      declination: { type: "number", required: false, description: "Magnetic declination", units: "degrees" },
      forceRtp: { type: "boolean", required: false, description: "Force RTP at low latitude instead of RTE", defaultValue: false },
    },
    metadataRequirements: ["valid TMI grid", "inclination and declination, or IGRF QC from mag.igrf"],
    scientificConstraints: [
      "RTP requires a valid grid plus field parameters or mag.igrf as a documented source of I/D.",
      "At |I|<10° the kernel writes RTE unless forceRtp is set.",
    ],
    qcRequirements: ["I and D recorded", "low-latitude warning", "RTE fallback documented if used"],
    viewerTypes: ["map"],
    interpretationLimits: [
      "RTP assumes induced magnetisation dominated by the present field. Remanence is not recovered.",
    ],
    expectedArtifacts: ["rtp_grid.asc", "rtp_qc.json"],
  }),
  mag({
    id: "mag.derivatives",
    version: "1.0.0",
    title: "MAGMAP derivatives",
    description: "FFT analytic signal, vertical derivatives, tilt, continuation, Euler solutions.",
    domain: "magnetics",
    kernelNodeIds: ["fft_derivatives", "euler_deconvolution"],
    dependsOn: ["mag.grid"],
    inputRoles: [{ role: "grid", adapterIds: ["magarrow"], required: true, description: "RTP or TMI grid" }],
    outputs: [
      { id: "magmap", type: "grid", description: "Derivative grids", viewer: "map" },
      { id: "euler", type: "vector", description: "Euler solutions", viewer: "table" },
    ],
    parameters: {
      continuationHeightM: { type: "number", required: false, description: "Upward continuation height", units: "m", defaultValue: 50 },
      structuralIndex: { type: "number", required: false, description: "Euler structural index", defaultValue: 1 },
    },
    metadataRequirements: ["grid from mag.grid (RTP preferred when mag.rtp ran)"],
    scientificConstraints: ["Derivatives amplify noise. Euler depths are model-dependent."],
    qcRequirements: ["source grid named", "product manifest"],
    viewerTypes: ["map", "table"],
    interpretationLimits: ["Derivative maps are enhancement products, not unique geology."],
    expectedArtifacts: ["analytic_signal.asc", "1vd.asc", "euler_solutions.csv", "magmap_manifest.json"],
  }),
  mag({
    id: "mag.lineaments",
    version: "1.0.0",
    title: "Lineament extraction",
    description: "THD non-maximum suppression lineaments.",
    domain: "magnetics",
    kernelNodeIds: ["lineament_extractor"],
    dependsOn: ["mag.derivatives"],
    inputRoles: [{ role: "grid", adapterIds: ["magarrow"], required: true, description: "THD or TMI grid" }],
    outputs: [{ id: "lineaments", type: "vector", description: "Lineament polylines", viewer: "map" }],
    parameters: {
      lineamentPercentile: { type: "number", required: false, description: "THD percentile threshold", defaultValue: 85 },
    },
    metadataRequirements: ["THD grid from mag.derivatives, or TMI grid fallback"],
    scientificConstraints: ["Lineaments are edge detections, not mapped faults."],
    qcRequirements: ["count of lineaments"],
    viewerTypes: ["map"],
    interpretationLimits: ["Do not treat extracted lineaments as field-verified structures."],
    expectedArtifacts: ["lineaments.geojson", "lineaments_qc.json"],
  }),
  mag({
    id: "mag.gis",
    version: "1.0.0",
    title: "GIS and report export",
    description: "Write GeoJSON flight path, maps, workbook, and report from magnetic products.",
    domain: "magnetics",
    kernelNodeIds: ["gis_export", "excel_export_adapter", "report_export_adapter"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Corrected points and any grids already written" }],
    outputs: [
      { id: "flight_path", type: "vector", description: "Flight path GeoJSON", viewer: "map" },
      { id: "workbook", type: "workbook", description: "Excel export", viewer: "file" },
      { id: "report", type: "report", description: "Run report", viewer: "file" },
    ],
    parameters: {},
    metadataRequirements: ["products already in the run folder"],
    scientificConstraints: ["Export only. Does not compute new geophysics."],
    qcRequirements: ["files written under G-AID Output"],
    viewerTypes: ["map", "file"],
    interpretationLimits: ["Exports inherit the limits of upstream magnetic products."],
    expectedArtifacts: ["flight_path.geojson", "diurnal_analysis.xlsx"],
  }),
  mag({
    id: "grav.ingest",
    version: "1.0.0",
    title: "Gravity ingest",
    description: "Read a documented gravity XYZ or reviewed mapped CSV into a canonical station table.",
    domain: "gravity",
    kernelNodeIds: ["gravity_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "gravity-stations",
        adapterIds: ["gravity-xyz", "gravity-csv"],
        required: true,
        description: "Supported gravity-contract catalog records (not unnamed XYZ)",
      },
    ],
    outputs: [
      { id: "gravity_canonical", type: "table", description: "Canonical gravity stations", viewer: "table" },
      { id: "gravity_ingest_qc", type: "qc", description: "Ingest QC and mapping provenance", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: ["named X/Y/Gravity columns or a reviewed mapping", "documented CRS", "documented units"],
    scientificConstraints: [
      "The first .xyz or .dat file is not gravity data.",
      "Column names that differ from X, Y, Gravity need a reviewed mapping stored with the catalog/plan.",
    ],
    qcRequirements: ["station count", "column mapping recorded", "CRS and units recorded"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not reduce gravity or imply geology."],
    expectedArtifacts: ["gravity_canonical.csv", "gravity_ingest_qc.json"],
  }),
  mag({
    id: "grav.freeair",
    version: "1.0.0",
    title: "Free-air anomaly",
    description: "Somigliana normal gravity and free-air correction. No density is applied.",
    domain: "gravity",
    kernelNodeIds: ["gravity_freeair"],
    dependsOn: ["grav.ingest"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Canonical gravity stations" }],
    outputs: [{ id: "free_air", type: "table", description: "Free-air anomaly mGal", viewer: "table" }],
    parameters: {
      surveyLatitude: { type: "number", required: false, description: "Geodetic latitude if X/Y are projected", units: "degrees" },
    },
    metadataRequirements: ["observed gravity in documented units", "elevation/height", "elevation datum", "geodetic latitude or surveyLatitude"],
    scientificConstraints: [
      "Somigliana needs geodetic latitude. Projected easting/northing is not latitude.",
      "Elevation datum is not assumed. Orthometric and ellipsoidal heights are not mixed.",
      "Units are not assumed to be mGal.",
    ],
    qcRequirements: ["mean free-air", "latitude source", "elevation datum", "unit conversion recorded"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Free-air anomaly is not a terrain-corrected Bouguer anomaly and is not a density body."],
    expectedArtifacts: ["gravity_freeair.csv", "gravity_freeair_qc.json"],
  }),
  mag({
    id: "grav.bouguer",
    version: "1.0.0",
    title: "Simple Bouguer correction",
    description: "Infinite-slab Bouguer correction using a user-supplied density. Bullard B only if requested.",
    domain: "gravity",
    kernelNodeIds: ["gravity_bouguer"],
    dependsOn: ["grav.freeair"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Free-air stations" }],
    outputs: [{ id: "bouguer", type: "table", description: "Simple Bouguer anomaly mGal", viewer: "table" }],
    parameters: {
      density: { type: "number", required: true, description: "Reduction density. Never assumed.", units: "g/cm3" },
      applyBullardB: { type: "boolean", required: false, description: "Apply LaFehr 1991 Bullard B spherical-cap term", defaultValue: false },
    },
    metadataRequirements: ["user density", "height used in free-air", "elevation datum"],
    scientificConstraints: [
      "Density is never defaulted to 2.67 g/cm³.",
      "This is simple Bouguer (infinite slab). It is not a terrain-corrected Bouguer anomaly.",
      "Near-zone terrain correction is the separate grav.terrain_near_zone capability and is off unless requested.",
      "Bullard B is off unless the user enables it.",
    ],
    qcRequirements: ["density recorded", "Bullard B flag", "mean Bouguer"],
    viewerTypes: ["table", "json"],
    interpretationLimits: [
      "Simple Bouguer is not a terrain-corrected Bouguer anomaly and is not a Complete Bouguer Anomaly. It does not prove lithology, mineralisation, or drill targets.",
    ],
    expectedArtifacts: ["gravity_bouguer.csv", "gravity_bouguer_qc.json"],
  }),
  mag({
    id: "grav.terrain_near_zone",
    version: "1.1.0",
    title: "Near-zone terrain-corrected Bouguer",
    description:
      "Nagy 1966 rectangular-prism terrain correction inside a user radius or bound DEM extent, added to simple Bouguer. This is not a Complete Bouguer Anomaly. Far-zone and intermediate-zone terrain are not implemented.",
    domain: "gravity",
    kernelNodeIds: ["gravity_terrain"],
    dependsOn: ["grav.bouguer"],
    inputRoles: [
      {
        role: "gravity-stations",
        adapterIds: ["gravity-xyz", "gravity-csv"],
        required: true,
        description: "Simple Bouguer stations from grav.bouguer",
      },
      {
        role: "dem",
        adapterIds: ["dem-ascii"],
        required: true,
        description: "Supported DEM ASCII catalog record with EPSG, Units=m, and ElevationDatum",
      },
    ],
    outputs: [
      {
        id: "near_zone_terrain_corrected_bouguer",
        type: "table",
        description: "Near-zone terrain-corrected Bouguer anomaly mGal (not Complete Bouguer)",
        viewer: "table",
      },
      { id: "terrain_qc", type: "qc", description: "Terrain-correction method, radius, DEM identity, coverage, Bullard B status", viewer: "json" },
    ],
    parameters: {
      density: { type: "number", required: true, description: "Reduction density. Never assumed.", units: "g/cm3" },
      terrainRadiusM: {
        type: "number",
        required: true,
        description: "Near-zone radius in metres. Required unless useDemExtent is true.",
        units: "m",
      },
      useDemExtent: {
        type: "boolean",
        required: false,
        description: "Use the bound DEM extent instead of a numeric radius. Still near-zone only.",
        defaultValue: false,
      },
    },
    metadataRequirements: [
      "supported dem-ascii catalog record",
      "horizontal CRS matching stations",
      "vertical datum on DEM and stations",
      "elevation units metres",
      "user density",
      "terrain radius or useDemExtent",
    ],
    scientificConstraints: [
      "Convention: Δg_NZTC = Δg_FA − 2πGρh [+ Bullard B if requested] + TC_Nagy(R or DEM extent).",
      "TC is |gz| of DEM-minus-slab prisms (Nagy 1966) inside the near-zone window. Always ≥ 0.",
      "Far-zone and intermediate-zone / Hayford–Bowie compartments are not implemented.",
      "Do not label this product Complete Bouguer Anomaly. It is not equivalent to a fully regional or commercial complete Bouguer.",
      "A DEM is never downloaded or invented.",
      "Density is never defaulted to 2.67 g/cm³.",
      "CRS is never silently reprojected.",
    ],
    qcRequirements: [
      "product_name: near-zone terrain-corrected Bouguer anomaly",
      "not_complete_bouguer: true",
      "DEM catalog ID and checksum",
      "radius or DEM-extent flag",
      "coverage fraction ≥ 0.95",
      "cell size",
      "vertical datum",
      "Bullard B status",
      "far_zone: false",
      "intermediate_zone: false",
    ],
    viewerTypes: ["table", "json", "map"],
    interpretationLimits: [
      "A near-zone terrain-corrected Bouguer anomaly is not lithology, mineralisation, or a drill target.",
      "Do not equate this product with Oasis montaj Complete Bouguer or any far-zone-corrected anomaly.",
    ],
    expectedArtifacts: [
      "near_zone_terrain_corrected_bouguer.csv",
      "near_zone_terrain_corrected_bouguer_qc.json",
      "near_zone_terrain_corrected_bouguer_grid.asc",
    ],
  }),
  mag({
    id: "grav.grid",
    version: "1.0.0",
    title: "Gravity grid",
    description: "Minimum-curvature grid of Bouguer or free-air stations.",
    domain: "gravity",
    kernelNodeIds: ["grav_gridder"],
    dependsOn: ["grav.freeair"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Reduced gravity stations" }],
    outputs: [{ id: "gravity_grid", type: "grid", description: "Bouguer or free-air grid", viewer: "map" }],
    parameters: {
      cellSizeM: { type: "number", required: false, description: "Grid cell size", units: "m" },
      gridTension: { type: "number", required: false, description: "Spline tension", defaultValue: 0.25 },
    },
    metadataRequirements: ["spatial x/y", "reduced gravity values", "documented CRS"],
    scientificConstraints: ["Gridding interpolates. It is not a measurement."],
    qcRequirements: ["crs_epsg", "cell size", "source column"],
    viewerTypes: ["map", "ascii-grid"],
    interpretationLimits: ["A colour grid is not a geological map."],
    expectedArtifacts: ["bouguer_grid.asc", "free_air_grid.asc", "near_zone_terrain_corrected_bouguer_grid.asc", "gravity_grid_qc.json"],
    // ASCII/GeoTIFF open through the Phase 4 map workspace. Gridding projected metres; EPSG:4326 is a documented limitation.
  }),
  mag({
    id: "grav.residual",
    version: "1.0.0",
    title: "Regional-residual separation",
    description: "Least-squares polynomial regional/residual split of a gravity grid.",
    domain: "gravity",
    kernelNodeIds: ["regional_residual"],
    dependsOn: ["grav.grid"],
    inputRoles: [{ role: "grid", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Gravity grid from grav.grid" }],
    outputs: [
      { id: "regional", type: "grid", description: "Regional gravity", viewer: "map" },
      { id: "residual", type: "grid", description: "Residual gravity", viewer: "map" },
    ],
    parameters: {
      polyOrder: { type: "number", required: false, description: "Polynomial order", defaultValue: 2 },
    },
    metadataRequirements: ["gravity grid"],
    scientificConstraints: ["Polynomial order is a modelling choice, not geology. Upward-continuation residuals are not in this pack."],
    qcRequirements: ["order recorded", "source grid named"],
    viewerTypes: ["map"],
    interpretationLimits: ["Residual highs/lows are not density bodies until modelled and field-checked."],
    expectedArtifacts: ["bouguer_regional.asc", "bouguer_residual.asc", "gravity_residual_qc.json"],
  }),
  mag({
    id: "grav.gis",
    version: "1.0.0",
    title: "Gravity GIS export",
    description: "Write station GeoJSON and grid products already in the run folder.",
    domain: "gravity",
    kernelNodeIds: ["grav_gis_export"],
    dependsOn: ["grav.ingest"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Canonical or reduced stations" }],
    outputs: [{ id: "stations", type: "vector", description: "Station GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["products already in the run folder"],
    scientificConstraints: ["Export only. Does not compute new geophysics or reproject silently."],
    qcRequirements: ["CRS on GeoJSON matches the documented survey CRS"],
    viewerTypes: ["map", "file"],
    interpretationLimits: ["Exports inherit the limits of upstream gravity products."],
    expectedArtifacts: ["gravity_stations.geojson"],
  }),
  mag({
    id: "grav.interpret",
    version: "1.0.0",
    title: "Gravity interpretation limits",
    description: "Evidence-bound report distinguishing observations, assumptions, uncertainty, and not-established conclusions.",
    domain: "gravity",
    kernelNodeIds: ["grav_interpret"],
    dependsOn: ["grav.grid"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Reduced gravity products" }],
    outputs: [{ id: "interpretation", type: "report", description: "Structured gravity interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest/free-air/Bouguer"],
    scientificConstraints: ["Does not infer lithology, mineralisation, density bodies, or drill targets as fact."],
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "A gravity anomaly is an observation. Density, geology, and drill targets are not established by this pack.",
      "Simple Bouguer and near-zone terrain-corrected Bouguer are different products. Neither is a Complete Bouguer Anomaly.",
    ],
    expectedArtifacts: ["gravity_interpretation.json"],
  }),
  mag({
    id: "ert.ingest",
    version: "1.0.0",
    title: "ERT ingest",
    description: "Read a documented G-AID ERT 1.0 Res2DInv-style .dat or a reviewed mapped CSV.",
    domain: "resistivity",
    kernelNodeIds: ["ert_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "Supported ERT-contract catalog records (not an arbitrary .dat file)",
      },
    ],
    outputs: [
      { id: "ert_canonical", type: "table", description: "Canonical ERT measurements", viewer: "table" },
      { id: "ert_ingest_qc", type: "qc", description: "Geometry, array, units, topography QC", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: ["array type", "electrode spacing", "apparent resistivity", "Units=ohm.m"],
    scientificConstraints: [
      "The first .dat file is not ERT data.",
      "Unknown array codes are refused. Array type is never defaulted.",
      "Topography is recorded when present and is not used in the 2-D forward kernel of this pack.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n measurements", "array type", "spacing", "units", "duplicate/outlier report"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not invert resistivity or imply geology."],
    expectedArtifacts: ["ert_canonical.csv", "ert_ingest_qc.json"],
  }),
  mag({
    id: "ert.pseudosection",
    version: "1.0.0",
    title: "ERT pseudosection",
    description: "Plot apparent resistivity at conventional pseudo-depth n·a/2. This is not a depth model.",
    domain: "resistivity",
    kernelNodeIds: ["ert_pseudosection"],
    dependsOn: ["ert.ingest"],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "Canonical ERT measurements",
      },
    ],
    outputs: [{ id: "pseudosection", type: "table", description: "x, pseudo-depth, ρa (ohm·m)", viewer: "section" }],
    parameters: {},
    metadataRequirements: ["canonical measurements with a, n, rhoa"],
    scientificConstraints: [
      "Pseudo-depth n·a/2 is a plotting convention, not inversion depth.",
      "Apparent resistivity is not true resistivity.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n points", "array type", "units ohm.m", "pseudo-depth labelled"],
    viewerTypes: ["section", "json"],
    interpretationLimits: [
      "A pseudosection is not a geological section, groundwater confirmation, or lithology.",
    ],
    expectedArtifacts: ["ert_pseudosection.csv", "ert_survey.json"],
  }),
  mag({
    id: "ert.invert2d",
    version: "1.0.0",
    title: "Experimental ERT 2-D inversion",
    description:
      "Experimental flat-topography 2.5-D smoothness invert. Not a production inversion pack. Not Res2DInv. Off the default ERT workflow until synthetic recovery meets declared true-resistivity thresholds.",
    domain: "resistivity",
    kernelNodeIds: ["ert_invert"],
    dependsOn: ["ert.pseudosection"],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "Canonical ERT measurements (≥ 8)",
      },
    ],
    outputs: [
      { id: "ert_2d_model", type: "table", description: "Smooth 2-D resistivity model (ohm·m)", viewer: "section" },
      { id: "ert_invert_qc", type: "qc", description: "Misfit, iterations, convergence, topography unused", viewer: "json" },
    ],
    parameters: {
      maxIterations: { type: "number", required: false, description: "Gauss–Newton iterations", defaultValue: 8 },
      dampingFactor: { type: "number", required: false, description: "Smoothness λ", defaultValue: 0.08 },
      maxMisfitPercent: { type: "number", required: false, description: "Fail if RMS misfit exceeds this percent", defaultValue: 25 },
    },
    metadataRequirements: ["≥ 8 measurements", "positive apparent resistivity", "documented array"],
    scientificConstraints: [
      "Experimental. Not a production-supported inversion workflow.",
      "Forward is a flat-topography 2.5-D finite-difference Poisson solve (Dey & Morrison 1979). Independent two-layer true resistivities are not recovered.",
      "Topography is not used in the forward kernel.",
      "3-D inversion is not implemented.",
      "Non-convergent inversions fail closed; a model is not written.",
      "Buried-target recovery is not established by an independent 2-D oracle.",
    ],
    qcRequirements: ["misfit percent", "iterations", "predicted vs observed ρa", "topography_used: false", "experimental: true"],
    viewerTypes: ["section", "json"],
    interpretationLimits: [
      "An experimental invert is not Res2DInv, not true resistivity, not lithology, not groundwater, not an ore body, and not a drill target.",
      "Failed or poorly resolved models must not generate affirmative interpretation language.",
    ],
    expectedArtifacts: ["ert_2d_model.csv", "ert_2d_model.json", "ert_invert_qc.json"],
    supportLevel: "experimental",
  }),
  mag({
    id: "ert.gis",
    version: "1.0.0",
    title: "ERT GIS export",
    description: "Write electrode midpoint GeoJSON when a documented CRS exists.",
    domain: "resistivity",
    kernelNodeIds: ["ert_gis_export"],
    dependsOn: ["ert.ingest"],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "Canonical ERT measurements with CRS",
      },
    ],
    outputs: [{ id: "electrodes", type: "vector", description: "Electrode midpoint GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["documented EPSG"],
    scientificConstraints: ["Export only. Does not invert or reproject silently."],
    qcRequirements: ["CRS on GeoJSON matches the documented survey CRS"],
    viewerTypes: ["map"],
    interpretationLimits: ["Electrode locations are survey geometry, not geology."],
    expectedArtifacts: ["ert_electrodes.geojson"],
    supportLevel: "supported",
  }),
  mag({
    id: "ert.interpret",
    version: "1.0.0",
    title: "ERT interpretation limits",
    description: "Evidence-bound report. Does not confirm groundwater, lithology, ore, or drill targets.",
    domain: "resistivity",
    kernelNodeIds: ["ert_interpret"],
    dependsOn: ["ert.pseudosection"],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "ERT products already in the run folder",
      },
    ],
    outputs: [{ id: "interpretation", type: "report", description: "Structured ERT interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest/pseudosection"],
    scientificConstraints: [
      "Does not infer groundwater, lithology, ore bodies, or drill targets as fact.",
      "Does not claim 3-D inversion or a production-supported invert.",
      "Does not speak affirmatively from a failed or poorly resolved model.",
    ],
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "A pseudosection is not a depth model.",
      "An experimental invert is not groundwater, lithology, ore-body, or drill-target evidence.",
      "Failed or poorly resolved models must not generate affirmative interpretation language.",
    ],
    expectedArtifacts: ["ert_interpretation.json"],
    supportLevel: "supported",
  }),
  mag({
    id: "rad.ingest",
    version: "1.0.0",
    title: "Radiometric ingest",
    description:
      "Read a documented G-AID RAD 1.0 already-corrected K/eU/eTh/TC table. Raw spectrometer files are not processed.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Supported RAD-contract catalog records (not an assay table or raw spectrum)",
      },
    ],
    outputs: [
      { id: "rad_canonical", type: "table", description: "Canonical radiometric samples", viewer: "table" },
      { id: "rad_ingest_qc", type: "qc", description: "Quantity, units, correction history, line QC", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: [
      "CRS",
      "Quantity=concentration or count_rate",
      "channel units",
      "Line column",
      "CorrectionHistory",
      "acquisition metadata",
    ],
    scientificConstraints: [
      "K, U, Th assay columns are not radiometric data.",
      "Quantity=counts and raw spectra are not supported processing inputs.",
      "Height correction, stripping, NASVD, dead-time, background, and concentration conversion are not live capabilities.",
      "G-AID does not re-apply or invent IAEA default corrections.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n", "n_lines", "quantity", "channels", "correction_history", "crs_epsg"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not map lithology, mineralisation, or alteration."],
    expectedArtifacts: ["rad_canonical.csv", "rad_ingest_qc.json"],
  }),
  mag({
    id: "rad.grid",
    version: "1.0.0",
    title: "Radiometric grid",
    description: "Minimum-curvature grid of each present already-corrected channel.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_grid"],
    dependsOn: ["rad.ingest"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Canonical radiometric samples",
      },
    ],
    outputs: [{ id: "rad_grids", type: "grid", description: "Per-channel ASCII/GeoTIFF grids", viewer: "map" }],
    parameters: {
      cellSizeM: { type: "number", required: false, description: "Grid cell size", units: "m" },
      gridTension: { type: "number", required: false, description: "Spline tension", defaultValue: 0.25 },
    },
    metadataRequirements: ["spatial x/y", "documented CRS", "at least one channel"],
    scientificConstraints: ["Gridding interpolates. It is not a measurement."],
    supportLevel: "supported",
    qcRequirements: ["channels", "quantity", "units"],
    viewerTypes: ["map", "ascii-grid"],
    interpretationLimits: ["A colour grid is not a geological map."],
    expectedArtifacts: ["rad_k_grid.asc", "rad_eu_grid.asc", "rad_eth_grid.asc", "rad_tc_grid.asc", "rad_grid_qc.json"],
  }),
  mag({
    id: "rad.ternary",
    version: "1.0.0",
    title: "Radiometric ternary",
    description: "K-eTh-eU RGB composite from concentration channels only. Skipped for count rates.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_ternary"],
    dependsOn: ["rad.grid"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Concentration K, eU, eTh",
      },
    ],
    outputs: [{ id: "rad_ternary", type: "report", description: "Ternary RGB JSON", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["Quantity=concentration", "K, eU, eTh"],
    scientificConstraints: [
      "Ternary is a percentile colour stretch (R=K, G=eTh, B=eU), not a classified lithology map.",
      "Not computed for count-rate or incomplete K-U-Th sets.",
    ],
    supportLevel: "supported",
    qcRequirements: ["justified", "assignment", "formula"],
    viewerTypes: ["json"],
    interpretationLimits: ["A ternary is not mineralisation, lithology, or alteration."],
    expectedArtifacts: ["rad_ternary.json", "rad_ternary_qc.json"],
  }),
  mag({
    id: "rad.ratios",
    version: "1.0.0",
    title: "Radiometric ratios",
    description: "eU/eTh, eU/K, and eTh/K from already-corrected concentrations.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_ratios"],
    dependsOn: ["rad.ingest"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Concentration channels",
      },
    ],
    outputs: [{ id: "rad_ratios", type: "table", description: "Ratio table", viewer: "table" }],
    parameters: {},
    metadataRequirements: ["Quantity=concentration", "paired channels"],
    scientificConstraints: [
      "Ratios are arithmetic on declared concentrations. Denominators near zero are clipped.",
      "A ratio is not a lithology or alteration index.",
    ],
    supportLevel: "supported",
    qcRequirements: ["formula", "n_clipped"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ratios are not lithology, alteration, or drill targets."],
    expectedArtifacts: ["rad_ratios.csv", "rad_ratio_qc.json"],
  }),
  mag({
    id: "rad.gis",
    version: "1.0.0",
    title: "Radiometric GIS export",
    description: "Write sample GeoJSON when a documented CRS exists.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_gis_export"],
    dependsOn: ["rad.ingest"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Canonical samples with CRS",
      },
    ],
    outputs: [{ id: "stations", type: "vector", description: "Sample GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["documented EPSG"],
    scientificConstraints: ["Export only. Does not reproject silently."],
    supportLevel: "supported",
    qcRequirements: ["CRS on GeoJSON matches the documented survey CRS"],
    viewerTypes: ["map"],
    interpretationLimits: ["Sample locations are survey geometry, not geology."],
    expectedArtifacts: ["rad_stations.geojson"],
  }),
  mag({
    id: "rad.interpret",
    version: "1.0.0",
    title: "Radiometric interpretation limits",
    description: "Evidence-bound report. Does not confirm mineralisation, lithology, alteration, or drill targets.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_interpret"],
    dependsOn: ["rad.ingest"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Radiometric products already in the run folder",
      },
    ],
    outputs: [{ id: "interpretation", type: "report", description: "Structured radiometric interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest"],
    scientificConstraints: [
      "Does not infer mineralisation, lithology, alteration, or drill targets as fact.",
      "Does not claim G-AID applied height, stripping, or concentration conversion.",
    ],
    supportLevel: "supported",
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "Already-corrected maps and ratios are not geology.",
      "Failed or skipped products must not generate affirmative interpretation language.",
    ],
    expectedArtifacts: ["rad_interpretation.json"],
  }),
];

const BY_ID = new Map(CAPABILITIES.map((capability) => [capability.id, capability]));

export function listCapabilities(): ScientificCapability[] {
  return CAPABILITIES.slice();
}

export function getCapability(id: string): ScientificCapability | undefined {
  return BY_ID.get(id as UserCapabilityId);
}

export function isRegisteredCapability(id: string): id is UserCapabilityId {
  return BY_ID.has(id as UserCapabilityId);
}

export function capabilityVersionMap(): Record<string, string> {
  const versions: Record<string, string> = {};
  for (const capability of CAPABILITIES) versions[capability.id] = capability.version;
  return versions;
}

export { USER_CAPABILITY_IDS };
