import { USER_CAPABILITY_IDS, type ScientificCapability, type UserCapabilityId } from "./types.ts";

function mag(partial: ScientificCapability): ScientificCapability {
  return partial;
}

const CAPABILITIES: ScientificCapability[] = [
  mag({
    id: "mag.diurnal",
    version: "1.0.0",
    title: "Diurnal correction",
    description: "Correct MagArrow rover samples with a GSM-19 base station.",
    domain: "magnetics",
    kernelNodeIds: [
      "file_discovery",
      "flight_path_cleaner",
      "time_synchronizer",
      "diurnal_corrector",
      "qc_engine",
    ],
    dependsOn: [],
    inputRoles: [
      {
        role: "rover",
        adapterIds: ["magarrow"],
        required: true,
        description: "Supported MagArrow airborne catalog records",
      },
      {
        role: "base",
        adapterIds: ["gsm19"],
        required: true,
        description: "Supported GSM-19 base-station catalog records",
      },
    ],
    outputs: [
      { id: "airborne_corrected", type: "table", description: "Diurnally corrected MagArrow samples", viewer: "table" },
      { id: "qc_report", type: "qc", description: "Diurnal QC statistics", viewer: "json" },
    ],
    parameters: {
      baseReference: {
        type: "string",
        required: true,
        description: "GSM-19 reference: mean_base, median_base, or first_sample",
        defaultValue: "mean_base",
      },
      surveyDate: { type: "string", required: false, description: "Survey date YYYY-MM-DD if GSM-19 header has no /ID stamp" },
    },
    metadataRequirements: ["rover timestamps", "base timestamps", "magnetic field nT"],
    scientificConstraints: [
      "Requires both MagArrow rover and GSM-19 base catalog records.",
      "Does not invent a survey date if the GSM-19 header has none.",
    ],
    qcRequirements: ["temporal overlap", "outlier report", "reference value recorded"],
    viewerTypes: ["table", "json"],
    interpretationLimits: [
      "Diurnal correction removes base-station variation only. It is not IGRF, levelling, or RTP.",
    ],
    expectedArtifacts: ["airborne_corrected.csv", "base_station_canonical.csv", "qc_report.json"],
  }),
  mag({
    id: "mag.igrf",
    version: "1.0.0",
    title: "IGRF removal",
    description: "Subtract IGRF-13 at each sample.",
    domain: "magnetics",
    kernelNodeIds: ["igrf_corrector"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Diurnally corrected points" }],
    outputs: [
      { id: "igrf_residual", type: "table", description: "IGRF residual nT plus I/D", viewer: "table" },
      { id: "igrf_qc", type: "qc", description: "Mean inclination/declination", viewer: "json" },
    ],
    parameters: {
      decimalYear: { type: "number", required: false, description: "Override survey decimal year" },
      surveyAltitudeM: { type: "number", required: false, description: "Default altitude when z is missing", units: "m" },
    },
    metadataRequirements: ["geodetic lat/lon", "timestamp or decimalYear"],
    scientificConstraints: ["IGRF-13 official SV window is 2020.0–2025.0; outside that range SV is extrapolated."],
    qcRequirements: ["mean I and D written", "extrapolation flag"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Residual is not RTP. Do not interpret uncorrected TMI as crustal anomaly after this step alone."],
    expectedArtifacts: ["airborne_igrf.csv", "igrf_qc.json"],
  }),
  mag({
    id: "mag.headingLag",
    version: "1.0.0",
    title: "Heading and lag",
    description: "Heading correction and reciprocal-line lag.",
    domain: "magnetics",
    kernelNodeIds: ["heading_lag_corrector"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Corrected MagArrow points" }],
    outputs: [{ id: "heading_lag", type: "table", description: "Heading/lag corrected samples", viewer: "table" }],
    parameters: {},
    metadataRequirements: ["track coordinates", "line structure for lag"],
    scientificConstraints: ["Lag is applied only when reciprocal lines support an estimate."],
    qcRequirements: ["heading RMS", "lag samples or reason not applied"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Does not replace tie-line levelling."],
    expectedArtifacts: ["airborne_heading_lag.csv", "heading_lag_qc.json"],
  }),
  mag({
    id: "mag.level",
    version: "1.0.0",
    title: "Tie-line levelling",
    description: "Statistical levelling of traverses against ties, then microlevelling.",
    domain: "magnetics",
    kernelNodeIds: ["tie_line_leveler", "microleveller"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Corrected MagArrow points" }],
    outputs: [{ id: "leveled", type: "table", description: "Levelled samples", viewer: "table" }],
    parameters: {
      tieRadiusM: { type: "number", required: false, description: "Tie intersection radius", units: "m", defaultValue: 25 },
    },
    metadataRequirements: ["line_id or geometry that distinguishes ties from traverses"],
    scientificConstraints: ["Ties are held; traverses shift. Requires identifiable tie/traverse structure."],
    qcRequirements: ["shift statistics", "microlevel applied flag"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Levelling can suppress geologic signal along-line if mis-parameterised."],
    expectedArtifacts: ["airborne_leveled.csv", "airborne_microleveled.csv", "leveling_qc.json"],
  }),
  mag({
    id: "mag.grid",
    version: "1.0.0",
    title: "Minimum-curvature grid",
    description: "Grid diurnally corrected spatial samples.",
    domain: "magnetics",
    kernelNodeIds: ["mag_gridder"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Corrected MagArrow points with x/y" }],
    outputs: [{ id: "tmi_grid", type: "grid", description: "TMI residual grid", viewer: "map" }],
    parameters: {
      cellSizeM: { type: "number", required: false, description: "Grid cell size", units: "m" },
      gridTension: { type: "number", required: false, description: "Spline tension", defaultValue: 0.25 },
    },
    metadataRequirements: ["spatial x/y", "corrected magnetic values"],
    scientificConstraints: ["Requires diurnally corrected spatial data. Does not grid raw unsupported tables."],
    qcRequirements: ["crs_epsg", "cell size", "grid dimensions"],
    viewerTypes: ["map", "ascii-grid"],
    interpretationLimits: ["Gridding interpolates; it is not a measurement. Cell size must be justified by line spacing."],
    expectedArtifacts: ["tmi_grid.asc", "tmi_grid.npz", "grid_qc.json"],
  }),
  mag({
    id: "mag.rtp",
    version: "1.0.0",
    title: "Reduction to the pole",
    description: "FFT RTP of a TMI grid using inclination and declination.",
    domain: "magnetics",
    kernelNodeIds: ["rtp_filter"],
    dependsOn: ["mag.grid"],
    inputRoles: [{ role: "grid", adapterIds: ["magarrow"], required: true, description: "TMI grid from mag.grid" }],
    outputs: [{ id: "rtp_grid", type: "grid", description: "RTP or documented RTE fallback", viewer: "map" }],
    parameters: {
      inclination: { type: "number", required: false, description: "Magnetic inclination", units: "degrees" },
      declination: { type: "number", required: false, description: "Magnetic declination", units: "degrees" },
      forceRtp: { type: "boolean", required: false, description: "Force RTP at low latitude instead of RTE", defaultValue: false },
    },
    metadataRequirements: ["valid TMI grid", "inclination and declination, or IGRF QC from mag.igrf"],
    scientificConstraints: [
      "RTP requires a valid grid plus field parameters or mag.igrf as a documented source of I/D.",
      "At |I|<10° the kernel writes RTE unless forceRtp is set.",
    ],
    qcRequirements: ["I and D recorded", "low-latitude warning", "RTE fallback documented if used"],
    viewerTypes: ["map"],
    interpretationLimits: [
      "RTP assumes induced magnetisation dominated by the present field. Remanence is not recovered.",
    ],
    expectedArtifacts: ["rtp_grid.asc", "rtp_qc.json"],
  }),
  mag({
    id: "mag.derivatives",
    version: "1.0.0",
    title: "MAGMAP derivatives",
    description: "FFT analytic signal, vertical derivatives, tilt, continuation, Euler solutions.",
    domain: "magnetics",
    kernelNodeIds: ["fft_derivatives", "euler_deconvolution"],
    dependsOn: ["mag.grid"],
    inputRoles: [{ role: "grid", adapterIds: ["magarrow"], required: true, description: "RTP or TMI grid" }],
    outputs: [
      { id: "magmap", type: "grid", description: "Derivative grids", viewer: "map" },
      { id: "euler", type: "vector", description: "Euler solutions", viewer: "table" },
    ],
    parameters: {
      continuationHeightM: { type: "number", required: false, description: "Upward continuation height", units: "m", defaultValue: 50 },
      structuralIndex: { type: "number", required: false, description: "Euler structural index", defaultValue: 1 },
    },
    metadataRequirements: ["grid from mag.grid (RTP preferred when mag.rtp ran)"],
    scientificConstraints: ["Derivatives amplify noise. Euler depths are model-dependent."],
    qcRequirements: ["source grid named", "product manifest"],
    viewerTypes: ["map", "table"],
    interpretationLimits: ["Derivative maps are enhancement products, not unique geology."],
    expectedArtifacts: ["analytic_signal.asc", "1vd.asc", "euler_solutions.csv", "magmap_manifest.json"],
  }),
  mag({
    id: "mag.lineaments",
    version: "1.0.0",
    title: "Lineament extraction",
    description: "THD non-maximum suppression lineaments.",
    domain: "magnetics",
    kernelNodeIds: ["lineament_extractor"],
    dependsOn: ["mag.derivatives"],
    inputRoles: [{ role: "grid", adapterIds: ["magarrow"], required: true, description: "THD or TMI grid" }],
    outputs: [{ id: "lineaments", type: "vector", description: "Lineament polylines", viewer: "map" }],
    parameters: {
      lineamentPercentile: { type: "number", required: false, description: "THD percentile threshold", defaultValue: 85 },
    },
    metadataRequirements: ["THD grid from mag.derivatives, or TMI grid fallback"],
    scientificConstraints: ["Lineaments are edge detections, not mapped faults."],
    qcRequirements: ["count of lineaments"],
    viewerTypes: ["map"],
    interpretationLimits: ["Do not treat extracted lineaments as field-verified structures."],
    expectedArtifacts: ["lineaments.geojson", "lineaments_qc.json"],
  }),
  mag({
    id: "mag.gis",
    version: "1.0.0",
    title: "GIS and report export",
    description: "Write GeoJSON flight path, maps, workbook, and report from magnetic products.",
    domain: "magnetics",
    kernelNodeIds: ["gis_export", "excel_export_adapter", "report_export_adapter"],
    dependsOn: ["mag.diurnal"],
    inputRoles: [{ role: "corrected-points", adapterIds: ["magarrow"], required: true, description: "Corrected points and any grids already written" }],
    outputs: [
      { id: "flight_path", type: "vector", description: "Flight path GeoJSON", viewer: "map" },
      { id: "workbook", type: "workbook", description: "Excel export", viewer: "file" },
      { id: "report", type: "report", description: "Run report", viewer: "file" },
    ],
    parameters: {},
    metadataRequirements: ["products already in the run folder"],
    scientificConstraints: ["Export only. Does not compute new geophysics."],
    qcRequirements: ["files written under G-AID Output"],
    viewerTypes: ["map", "file"],
    interpretationLimits: ["Exports inherit the limits of upstream magnetic products."],
    expectedArtifacts: ["flight_path.geojson", "diurnal_analysis.xlsx"],
  }),
  mag({
    id: "grav.ingest",
    version: "1.0.0",
    title: "Gravity ingest",
    description: "Read a documented gravity XYZ or reviewed mapped CSV into a canonical station table.",
    domain: "gravity",
    kernelNodeIds: ["gravity_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "gravity-stations",
        adapterIds: ["gravity-xyz", "gravity-csv"],
        required: true,
        description: "Supported gravity-contract catalog records (not unnamed XYZ)",
      },
    ],
    outputs: [
      { id: "gravity_canonical", type: "table", description: "Canonical gravity stations", viewer: "table" },
      { id: "gravity_ingest_qc", type: "qc", description: "Ingest QC and mapping provenance", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: ["named X/Y/Gravity columns or a reviewed mapping", "documented CRS", "documented units"],
    scientificConstraints: [
      "The first .xyz or .dat file is not gravity data.",
      "Column names that differ from X, Y, Gravity need a reviewed mapping stored with the catalog/plan.",
    ],
    qcRequirements: ["station count", "column mapping recorded", "CRS and units recorded"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not reduce gravity or imply geology."],
    expectedArtifacts: ["gravity_canonical.csv", "gravity_ingest_qc.json"],
  }),
  mag({
    id: "grav.freeair",
    version: "1.0.0",
    title: "Free-air anomaly",
    description: "Somigliana normal gravity and free-air correction. No density is applied.",
    domain: "gravity",
    kernelNodeIds: ["gravity_freeair"],
    dependsOn: ["grav.ingest"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Canonical gravity stations" }],
    outputs: [{ id: "free_air", type: "table", description: "Free-air anomaly mGal", viewer: "table" }],
    parameters: {
      surveyLatitude: { type: "number", required: false, description: "Geodetic latitude if X/Y are projected", units: "degrees" },
    },
    metadataRequirements: ["observed gravity in documented units", "elevation/height", "elevation datum", "geodetic latitude or surveyLatitude"],
    scientificConstraints: [
      "Somigliana needs geodetic latitude. Projected easting/northing is not latitude.",
      "Elevation datum is not assumed. Orthometric and ellipsoidal heights are not mixed.",
      "Units are not assumed to be mGal.",
    ],
    qcRequirements: ["mean free-air", "latitude source", "elevation datum", "unit conversion recorded"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Free-air anomaly is not a terrain-corrected Bouguer anomaly and is not a density body."],
    expectedArtifacts: ["gravity_freeair.csv", "gravity_freeair_qc.json"],
  }),
  mag({
    id: "grav.bouguer",
    version: "1.0.0",
    title: "Simple Bouguer correction",
    description: "Infinite-slab Bouguer correction using a user-supplied density. Bullard B only if requested.",
    domain: "gravity",
    kernelNodeIds: ["gravity_bouguer"],
    dependsOn: ["grav.freeair"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Free-air stations" }],
    outputs: [{ id: "bouguer", type: "table", description: "Simple Bouguer anomaly mGal", viewer: "table" }],
    parameters: {
      density: { type: "number", required: true, description: "Reduction density. Never assumed.", units: "g/cm3" },
      applyBullardB: { type: "boolean", required: false, description: "Apply LaFehr 1991 Bullard B spherical-cap term", defaultValue: false },
    },
    metadataRequirements: ["user density", "height used in free-air", "elevation datum"],
    scientificConstraints: [
      "Density is never defaulted to 2.67 g/cm³.",
      "This is simple Bouguer (infinite slab). It is not a terrain-corrected Bouguer anomaly.",
      "Near-zone terrain correction is the separate grav.terrain_near_zone capability and is off unless requested.",
      "Bullard B is off unless the user enables it.",
    ],
    qcRequirements: ["density recorded", "Bullard B flag", "mean Bouguer"],
    viewerTypes: ["table", "json"],
    interpretationLimits: [
      "Simple Bouguer is not a terrain-corrected Bouguer anomaly. It does not prove lithology, mineralisation, or drill targets.",
    ],
    expectedArtifacts: ["gravity_bouguer.csv", "gravity_bouguer_qc.json"],
  }),
  mag({
    id: "grav.terrain_near_zone",
    version: "1.2.0",
    title: "Near-zone terrain-corrected Bouguer",
    description:
      "Nagy 1966 rectangular-prism terrain correction inside a user radius or bound DEM extent, added to simple Bouguer. Intermediate- and far-zone rings are separate capabilities on the same kernel. Spherical far-zone treatment, Hayford–Bowie geometry, global coverage, and atmospheric correction are excluded.",
    domain: "gravity",
    kernelNodeIds: ["gravity_terrain"],
    dependsOn: ["grav.bouguer"],
    inputRoles: [
      {
        role: "gravity-stations",
        adapterIds: ["gravity-xyz", "gravity-csv"],
        required: true,
        description: "Simple Bouguer stations from grav.bouguer",
      },
      {
        role: "dem",
        adapterIds: ["dem-ascii"],
        required: true,
        description: "Supported DEM ASCII catalog record with EPSG, Units=m, and ElevationDatum",
      },
    ],
    outputs: [
      {
        id: "near_zone_terrain_corrected_bouguer",
        type: "table",
        description: "Near-zone terrain-corrected Bouguer anomaly mGal",
        viewer: "table",
      },
      { id: "terrain_qc", type: "qc", description: "Terrain-correction method, radius, DEM identity, coverage, Bullard B status", viewer: "json" },
    ],
    parameters: {
      density: { type: "number", required: true, description: "Reduction density. Never assumed.", units: "g/cm3" },
      terrainRadiusM: {
        type: "number",
        required: true,
        description: "Near-zone radius in metres. Required unless useDemExtent is true.",
        units: "m",
      },
      useDemExtent: {
        type: "boolean",
        required: false,
        description: "Use the bound DEM extent instead of a numeric radius. Near-zone window only.",
        defaultValue: false,
      },
    },
    metadataRequirements: [
      "supported dem-ascii catalog record",
      "horizontal CRS matching stations",
      "vertical datum on DEM and stations",
      "elevation units metres",
      "user density",
      "terrain radius or useDemExtent",
    ],
    scientificConstraints: [
      "Convention: Δg_NZTC = Δg_FA − 2πGρh [+ Bullard B if requested] + TC_Nagy(R or DEM extent).",
      "TC is |gz| of DEM-minus-slab prisms (Nagy 1966) inside the near-zone window. Always ≥ 0.",
      "Intermediate- and far-zone rings require grav.terrain_intermediate_zone / grav.terrain_far_zone. Hayford–Bowie compartments are not implemented.",
      "Spherical far-zone treatment, Hayford–Bowie or equivalent geometry, global/adequate terrain coverage, and atmospheric correction are excluded.",
      "A DEM is never downloaded or invented.",
      "Density is never defaulted to 2.67 g/cm³.",
      "CRS is never silently reprojected.",
    ],
    qcRequirements: [
      "product_name: near-zone terrain-corrected Bouguer anomaly",
      "not_complete_bouguer: true",
      "DEM catalog ID and checksum",
      "radius or DEM-extent flag",
      "coverage fraction ≥ 0.95",
      "cell size",
      "vertical datum",
      "Bullard B status",
      "far_zone recorded (false unless a covering far ring actually ran)",
      "intermediate_zone recorded (false unless a covering intermediate ring actually ran)",
    ],
    viewerTypes: ["table", "json", "map"],
    interpretationLimits: [
      "A near-zone terrain-corrected Bouguer anomaly is not lithology, mineralisation, or a drill target.",
      "Do not equate this product with Oasis montaj full-convention Bouguer or any spherical far-zone product.",
    ],
    expectedArtifacts: [
      "near_zone_terrain_corrected_bouguer.csv",
      "near_zone_terrain_corrected_bouguer_qc.json",
      "near_zone_terrain_corrected_bouguer_grid.asc",
    ],
  }),
  mag({
    id: "grav.terrain_intermediate_zone",
    version: "1.0.0",
    title: "Intermediate-zone terrain correction",
    description:
      "Planar Nagy prism terrain in the annulus from the near-zone radius out to min(166.7 km, bound DEM). Aggregated cells may be used. Hayford–Bowie compartments are not implemented. Spherical far-zone treatment, global coverage, and atmospheric correction are excluded.",
    domain: "gravity",
    kernelNodeIds: ["gravity_terrain"],
    dependsOn: ["grav.terrain_near_zone"],
    inputRoles: [
      {
        role: "gravity-stations",
        adapterIds: ["gravity-xyz", "gravity-csv"],
        required: true,
        description: "Simple Bouguer stations from grav.bouguer",
      },
      {
        role: "dem",
        adapterIds: ["dem-ascii"],
        required: true,
        description: "Supported DEM ASCII catalog record covering the intermediate annulus",
      },
    ],
    outputs: [
      {
        id: "intermediate_terrain_correction",
        type: "table",
        description: "Intermediate-zone terrain correction mGal on the same near-zone product",
        viewer: "table",
      },
    ],
    parameters: {
      density: { type: "number", required: true, description: "Reduction density. Never assumed.", units: "g/cm3" },
      intermediateRadiusM: {
        type: "number",
        required: false,
        description: "Outer radius of the intermediate annulus. Default 166700 m (Hayford–Bowie zone O), clipped to the bound DEM.",
        units: "m",
        defaultValue: 166700,
      },
      outerCellSizeM: {
        type: "number",
        required: false,
        description: "Target cell size for aggregated outer-zone prisms",
        units: "m",
        defaultValue: 500,
      },
    },
    metadataRequirements: [
      "supported dem-ascii catalog record covering the annulus",
      "horizontal CRS matching stations",
      "vertical datum on DEM and stations",
      "near-zone radius already documented",
    ],
    scientificConstraints: [
      "Convention: planar Nagy annulus R_near → min(R_int, DEM coverage). Default R_int = 166.7 km.",
      "The ring is skipped when DEM coverage inside it is < 95%. Terrain outside the bound DEM is not invented or downloaded.",
      "Hayford–Bowie compartment geometry is not implemented. Only the 166.7 km outer radius number is used.",
      "Hayford–Bowie compartment geometry is not implemented. Only the 166.7 km outer radius number is used. Spherical far-zone treatment, global coverage, and atmospheric correction remain excluded.",
    ],
    qcRequirements: [
      "intermediate.applied true or a recorded skip reason",
      "requested vs effective radius",
      "coverage_mean",
      "not_complete_bouguer: true",
    ],
    viewerTypes: ["table", "json", "map"],
    interpretationLimits: [
      "An intermediate-zone planar ring on a local DEM is not a Hayford–Bowie complete terrain correction.",
      "Do not equate this product with Oasis montaj full-convention Bouguer.",
    ],
    expectedArtifacts: [
      "near_zone_terrain_corrected_bouguer.csv",
      "near_zone_terrain_corrected_bouguer_qc.json",
    ],
  }),
  mag({
    id: "grav.terrain_far_zone",
    version: "1.0.0",
    title: "Far-zone terrain correction",
    description:
      "Planar Nagy prism terrain beyond 166.7 km, only when a bound DEM actually covers the requested far radius. G-AID never downloads ETOPO/SRTM. Spherical-Earth far-zone theory is not implemented. Atmospheric correction is excluded.",
    domain: "gravity",
    kernelNodeIds: ["gravity_terrain"],
    dependsOn: ["grav.terrain_near_zone"],
    inputRoles: [
      {
        role: "gravity-stations",
        adapterIds: ["gravity-xyz", "gravity-csv"],
        required: true,
        description: "Simple Bouguer stations from grav.bouguer",
      },
      {
        role: "dem",
        adapterIds: ["dem-ascii"],
        required: true,
        description: "Supported DEM ASCII catalog record that must cover farRadiusM to apply the ring",
      },
    ],
    outputs: [
      {
        id: "far_terrain_correction",
        type: "table",
        description: "Far-zone terrain correction mGal when the bound DEM covers the ring (otherwise skipped)",
        viewer: "table",
      },
    ],
    parameters: {
      density: { type: "number", required: true, description: "Reduction density. Never assumed.", units: "g/cm3" },
      farRadiusM: {
        type: "number",
        required: true,
        description: "Outer radius of the far annulus in metres. Required to attempt far-zone TC. No global default. Must exceed 166.7 km.",
        units: "m",
      },
      outerCellSizeM: {
        type: "number",
        required: false,
        description: "Target cell size for aggregated outer-zone prisms",
        units: "m",
        defaultValue: 500,
      },
    },
    metadataRequirements: [
      "farRadiusM",
      "supported dem-ascii catalog record covering farRadiusM",
      "horizontal CRS matching stations",
      "vertical datum on DEM and stations",
    ],
    scientificConstraints: [
      "Far-zone starts at max(applied intermediate outer radius, 166.7 km).",
      "Applied only when the bound DEM covers farRadiusM with ≥ 95% coverage. Missing global DEM is a skip, never a silent pass.",
      "Planar Nagy only. Spherical-Earth far-zone theory, atmospheric correction, and Hayford–Bowie compartments are excluded.",
      "A DEM is never downloaded or invented.",
      "Spherical far-zone treatment, Hayford–Bowie geometry, global coverage, and atmospheric correction are excluded.",
    ],
    qcRequirements: [
      "far.applied true or a recorded skip reason",
      "requested radius",
      "coverage_mean when attempted",
      "complete_bouguer: false",
    ],
    viewerTypes: ["table", "json", "map"],
    interpretationLimits: [
      "A skipped or planar far ring does not supply spherical far-zone treatment, Hayford–Bowie geometry, global coverage, or atmospheric correction.",
      "Do not equate this product with Oasis montaj full-convention Bouguer or any spherical far-zone product.",
    ],
    expectedArtifacts: [
      "near_zone_terrain_corrected_bouguer.csv",
      "near_zone_terrain_corrected_bouguer_qc.json",
    ],
  }),
  mag({
    id: "grav.grid",
    version: "1.0.0",
    title: "Gravity grid",
    description: "Minimum-curvature grid of Bouguer or free-air stations.",
    domain: "gravity",
    kernelNodeIds: ["grav_gridder"],
    dependsOn: ["grav.freeair"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Reduced gravity stations" }],
    outputs: [{ id: "gravity_grid", type: "grid", description: "Bouguer or free-air grid", viewer: "map" }],
    parameters: {
      cellSizeM: { type: "number", required: false, description: "Grid cell size", units: "m" },
      gridTension: { type: "number", required: false, description: "Spline tension", defaultValue: 0.25 },
    },
    metadataRequirements: ["spatial x/y", "reduced gravity values", "documented CRS"],
    scientificConstraints: ["Gridding interpolates. It is not a measurement."],
    qcRequirements: ["crs_epsg", "cell size", "source column"],
    viewerTypes: ["map", "ascii-grid"],
    interpretationLimits: ["A colour grid is not a geological map."],
    expectedArtifacts: ["bouguer_grid.asc", "free_air_grid.asc", "near_zone_terrain_corrected_bouguer_grid.asc", "gravity_grid_qc.json"],
    // ASCII/GeoTIFF open through the Phase 4 map workspace. Gridding projected metres; EPSG:4326 is a documented limitation.
  }),
  mag({
    id: "grav.residual",
    version: "1.0.0",
    title: "Regional-residual separation",
    description: "Least-squares polynomial regional/residual split of a gravity grid.",
    domain: "gravity",
    kernelNodeIds: ["regional_residual"],
    dependsOn: ["grav.grid"],
    inputRoles: [{ role: "grid", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Gravity grid from grav.grid" }],
    outputs: [
      { id: "regional", type: "grid", description: "Regional gravity", viewer: "map" },
      { id: "residual", type: "grid", description: "Residual gravity", viewer: "map" },
    ],
    parameters: {
      polyOrder: { type: "number", required: false, description: "Polynomial order", defaultValue: 2 },
    },
    metadataRequirements: ["gravity grid"],
    scientificConstraints: ["Polynomial order is a modelling choice, not geology. Upward-continuation residuals are not in this pack."],
    qcRequirements: ["order recorded", "source grid named"],
    viewerTypes: ["map"],
    interpretationLimits: ["Residual highs/lows are not density bodies until modelled and field-checked."],
    expectedArtifacts: ["bouguer_regional.asc", "bouguer_residual.asc", "gravity_residual_qc.json"],
  }),
  mag({
    id: "grav.gis",
    version: "1.0.0",
    title: "Gravity GIS export",
    description: "Write station GeoJSON and grid products already in the run folder.",
    domain: "gravity",
    kernelNodeIds: ["grav_gis_export"],
    dependsOn: ["grav.ingest"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Canonical or reduced stations" }],
    outputs: [{ id: "stations", type: "vector", description: "Station GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["products already in the run folder"],
    scientificConstraints: ["Export only. Does not compute new geophysics or reproject silently."],
    qcRequirements: ["CRS on GeoJSON matches the documented survey CRS"],
    viewerTypes: ["map", "file"],
    interpretationLimits: ["Exports inherit the limits of upstream gravity products."],
    expectedArtifacts: ["gravity_stations.geojson"],
  }),
  mag({
    id: "grav.interpret",
    version: "1.0.0",
    title: "Gravity interpretation limits",
    description: "Evidence-bound report distinguishing observations, assumptions, uncertainty, and not-established conclusions.",
    domain: "gravity",
    kernelNodeIds: ["grav_interpret"],
    dependsOn: ["grav.grid"],
    inputRoles: [{ role: "gravity-stations", adapterIds: ["gravity-xyz", "gravity-csv"], required: true, description: "Reduced gravity products" }],
    outputs: [{ id: "interpretation", type: "report", description: "Structured gravity interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest/free-air/Bouguer"],
    scientificConstraints: ["Does not infer lithology, mineralisation, density bodies, or drill targets as fact."],
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "A gravity anomaly is an observation. Density, geology, and drill targets are not established by this pack.",
      "Simple Bouguer, near-zone, and zoned planar terrain-corrected Bouguer are different products. None includes spherical far-zone treatment, Hayford–Bowie geometry, global coverage, or atmospheric correction.",
    ],
    expectedArtifacts: ["gravity_interpretation.json"],
  }),
  mag({
    id: "ert.ingest",
    version: "1.0.0",
    title: "ERT ingest",
    description: "Read a documented G-AID ERT 1.0 Res2DInv-style .dat or a reviewed mapped CSV.",
    domain: "resistivity",
    kernelNodeIds: ["ert_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "Supported ERT-contract catalog records (not an arbitrary .dat file)",
      },
    ],
    outputs: [
      { id: "ert_canonical", type: "table", description: "Canonical ERT measurements", viewer: "table" },
      { id: "ert_ingest_qc", type: "qc", description: "Geometry, array, units, topography QC", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: ["array type", "electrode spacing", "apparent resistivity", "Units=ohm.m"],
    scientificConstraints: [
      "The first .dat file is not ERT data.",
      "Unknown array codes are refused. Array type is never defaulted.",
      "Topography is recorded when present and is not used in the 2-D forward kernel of this pack.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n measurements", "array type", "spacing", "units", "duplicate/outlier report"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not invert resistivity or imply geology."],
    expectedArtifacts: ["ert_canonical.csv", "ert_ingest_qc.json"],
  }),
  mag({
    id: "ert.pseudosection",
    version: "1.0.0",
    title: "ERT pseudosection",
    description: "Plot apparent resistivity at conventional pseudo-depth n·a/2. This is not a depth model.",
    domain: "resistivity",
    kernelNodeIds: ["ert_pseudosection"],
    dependsOn: ["ert.ingest"],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "Canonical ERT measurements",
      },
    ],
    outputs: [{ id: "pseudosection", type: "table", description: "x, pseudo-depth, ρa (ohm·m)", viewer: "section" }],
    parameters: {},
    metadataRequirements: ["canonical measurements with a, n, rhoa"],
    scientificConstraints: [
      "Pseudo-depth n·a/2 is a plotting convention, not inversion depth.",
      "Apparent resistivity is not true resistivity.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n points", "array type", "units ohm.m", "pseudo-depth labelled"],
    viewerTypes: ["section", "json"],
    interpretationLimits: [
      "A pseudosection is not a geological section, groundwater confirmation, or lithology.",
    ],
    expectedArtifacts: ["ert_pseudosection.csv", "ert_survey.json"],
  }),
  mag({
    id: "ert.invert2d",
    version: "1.0.0",
    title: "Experimental ERT 2-D inversion",
    description:
      "Experimental flat-topography 2.5-D smoothness invert. Not a production inversion pack. Not Res2DInv. Off the default ERT workflow until synthetic recovery meets declared true-resistivity thresholds.",
    domain: "resistivity",
    kernelNodeIds: ["ert_invert"],
    dependsOn: ["ert.pseudosection"],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "Canonical ERT measurements (≥ 8)",
      },
    ],
    outputs: [
      { id: "ert_2d_model", type: "table", description: "Smooth 2-D resistivity model (ohm·m)", viewer: "section" },
      { id: "ert_invert_qc", type: "qc", description: "Misfit, iterations, convergence, topography unused", viewer: "json" },
    ],
    parameters: {
      maxIterations: { type: "number", required: false, description: "Gauss–Newton iterations", defaultValue: 8 },
      dampingFactor: { type: "number", required: false, description: "Smoothness λ", defaultValue: 0.08 },
      maxMisfitPercent: { type: "number", required: false, description: "Fail if RMS misfit exceeds this percent", defaultValue: 25 },
    },
    metadataRequirements: ["≥ 8 measurements", "positive apparent resistivity", "documented array"],
    scientificConstraints: [
      "Experimental. Not a production-supported inversion workflow.",
      "Forward is a flat-topography 2.5-D finite-difference Poisson solve (Dey & Morrison 1979). Independent two-layer true resistivities are not recovered.",
      "Topography is not used in the forward kernel.",
      "3-D inversion is not implemented.",
      "Non-convergent inversions fail closed; a model is not written.",
      "Buried-target recovery is not established by an independent 2-D oracle.",
    ],
    qcRequirements: ["misfit percent", "iterations", "predicted vs observed ρa", "topography_used: false", "experimental: true"],
    viewerTypes: ["section", "json"],
    interpretationLimits: [
      "An experimental invert is not Res2DInv, not true resistivity, not lithology, not groundwater, not an ore body, and not a drill target.",
      "Failed or poorly resolved models must not generate affirmative interpretation language.",
    ],
    expectedArtifacts: ["ert_2d_model.csv", "ert_2d_model.json", "ert_invert_qc.json"],
    supportLevel: "experimental",
  }),
  mag({
    id: "ert.gis",
    version: "1.0.0",
    title: "ERT GIS export",
    description: "Write electrode midpoint GeoJSON when a documented CRS exists.",
    domain: "resistivity",
    kernelNodeIds: ["ert_gis_export"],
    dependsOn: ["ert.ingest"],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "Canonical ERT measurements with CRS",
      },
    ],
    outputs: [{ id: "electrodes", type: "vector", description: "Electrode midpoint GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["documented EPSG"],
    scientificConstraints: ["Export only. Does not invert or reproject silently."],
    qcRequirements: ["CRS on GeoJSON matches the documented survey CRS"],
    viewerTypes: ["map"],
    interpretationLimits: ["Electrode locations are survey geometry, not geology."],
    expectedArtifacts: ["ert_electrodes.geojson"],
    supportLevel: "supported",
  }),
  mag({
    id: "ert.interpret",
    version: "1.0.0",
    title: "ERT interpretation limits",
    description: "Evidence-bound report. Does not confirm groundwater, lithology, ore, or drill targets.",
    domain: "resistivity",
    kernelNodeIds: ["ert_interpret"],
    dependsOn: ["ert.pseudosection"],
    inputRoles: [
      {
        role: "ert-measurements",
        adapterIds: ["ert-dat", "ert-csv"],
        required: true,
        description: "ERT products already in the run folder",
      },
    ],
    outputs: [{ id: "interpretation", type: "report", description: "Structured ERT interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest/pseudosection"],
    scientificConstraints: [
      "Does not infer groundwater, lithology, ore bodies, or drill targets as fact.",
      "Does not claim 3-D inversion or a production-supported invert.",
      "Does not speak affirmatively from a failed or poorly resolved model.",
    ],
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "A pseudosection is not a depth model.",
      "An experimental invert is not groundwater, lithology, ore-body, or drill-target evidence.",
      "Failed or poorly resolved models must not generate affirmative interpretation language.",
    ],
    expectedArtifacts: ["ert_interpretation.json"],
    supportLevel: "supported",
  }),
  mag({
    id: "rad.ingest",
    version: "1.0.0",
    title: "Radiometric ingest",
    description:
      "Read a documented G-AID RAD 1.0 already-corrected K/eU/eTh/TC table. Raw spectrometer files are not processed.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Supported RAD-contract catalog records (not an assay table or raw spectrum)",
      },
    ],
    outputs: [
      { id: "rad_canonical", type: "table", description: "Canonical radiometric samples", viewer: "table" },
      { id: "rad_ingest_qc", type: "qc", description: "Quantity, units, correction history, line QC", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: [
      "CRS",
      "Quantity=concentration or count_rate",
      "channel units",
      "Line column",
      "CorrectionHistory",
      "acquisition metadata",
    ],
    scientificConstraints: [
      "K, U, Th assay columns are not radiometric data.",
      "Quantity=counts and raw spectra are not supported processing inputs.",
      "Height correction, stripping, NASVD, dead-time, background, and concentration conversion are not live capabilities.",
      "G-AID does not re-apply or invent IAEA default corrections.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n", "n_lines", "quantity", "channels", "correction_history", "crs_epsg"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not map lithology, mineralisation, or alteration."],
    expectedArtifacts: ["rad_canonical.csv", "rad_ingest_qc.json"],
  }),
  mag({
    id: "rad.grid",
    version: "1.0.0",
    title: "Radiometric grid",
    description: "Minimum-curvature grid of each present already-corrected channel.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_grid"],
    dependsOn: ["rad.ingest"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Canonical radiometric samples",
      },
    ],
    outputs: [{ id: "rad_grids", type: "grid", description: "Per-channel ASCII/GeoTIFF grids", viewer: "map" }],
    parameters: {
      cellSizeM: { type: "number", required: false, description: "Grid cell size", units: "m" },
      gridTension: { type: "number", required: false, description: "Spline tension", defaultValue: 0.25 },
    },
    metadataRequirements: ["spatial x/y", "documented CRS", "at least one channel"],
    scientificConstraints: ["Gridding interpolates. It is not a measurement."],
    supportLevel: "supported",
    qcRequirements: ["channels", "quantity", "units"],
    viewerTypes: ["map", "ascii-grid"],
    interpretationLimits: ["A colour grid is not a geological map."],
    expectedArtifacts: ["rad_k_grid.asc", "rad_eu_grid.asc", "rad_eth_grid.asc", "rad_tc_grid.asc", "rad_grid_qc.json"],
  }),
  mag({
    id: "rad.ternary",
    version: "1.0.0",
    title: "Radiometric ternary",
    description: "K-eTh-eU RGB composite from concentration channels only. Skipped for count rates.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_ternary"],
    dependsOn: ["rad.grid"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Concentration K, eU, eTh",
      },
    ],
    outputs: [{ id: "rad_ternary", type: "report", description: "Ternary RGB JSON", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["Quantity=concentration", "K, eU, eTh", "documented %K / ppm eU / ppm eTh units"],
    scientificConstraints: [
      "Ternary is a percentile colour stretch (R=K, G=eTh, B=eU), not a classified lithology map.",
      "Not computed for count-rate, unknown units, or incomplete K-U-Th sets.",
    ],
    supportLevel: "supported",
    qcRequirements: ["justified", "assignment", "formula"],
    viewerTypes: ["json"],
    interpretationLimits: ["A ternary is not mineralisation, lithology, or alteration."],
    expectedArtifacts: ["rad_ternary.json", "rad_ternary_qc.json"],
  }),
  mag({
    id: "rad.ratios",
    version: "1.0.0",
    title: "Radiometric ratios",
    description: "eU/eTh, eU/K, and eTh/K from already-corrected concentrations.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_ratios"],
    dependsOn: ["rad.ingest"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Concentration channels",
      },
    ],
    outputs: [{ id: "rad_ratios", type: "table", description: "Ratio table", viewer: "table" }],
    parameters: {},
    metadataRequirements: ["Quantity=concentration", "paired channels", "documented concentration units"],
    scientificConstraints: [
      "Ratios are arithmetic on declared concentrations. Denominators near zero are clipped.",
      "A ratio is not a lithology or alteration index.",
    ],
    supportLevel: "supported",
    qcRequirements: ["formula", "n_clipped"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ratios are not lithology, alteration, or drill targets."],
    expectedArtifacts: ["rad_ratios.csv", "rad_ratio_qc.json"],
  }),
  mag({
    id: "rad.gis",
    version: "1.0.0",
    title: "Radiometric GIS export",
    description: "Write sample GeoJSON when a documented CRS exists.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_gis_export"],
    dependsOn: ["rad.ingest"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Canonical samples with CRS",
      },
    ],
    outputs: [{ id: "stations", type: "vector", description: "Sample GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["documented EPSG"],
    scientificConstraints: ["Export only. Does not reproject silently."],
    supportLevel: "supported",
    qcRequirements: ["CRS on GeoJSON matches the documented survey CRS"],
    viewerTypes: ["map"],
    interpretationLimits: ["Sample locations are survey geometry, not geology."],
    expectedArtifacts: ["rad_stations.geojson"],
  }),
  mag({
    id: "rad.interpret",
    version: "1.0.0",
    title: "Radiometric interpretation limits",
    description: "Evidence-bound report. Does not confirm mineralisation, lithology, alteration, or drill targets.",
    domain: "radiometrics",
    kernelNodeIds: ["rad_interpret"],
    dependsOn: ["rad.ingest"],
    inputRoles: [
      {
        role: "radiometric-stations",
        adapterIds: ["radiometric-csv", "radiometric-xyz"],
        required: true,
        description: "Radiometric products already in the run folder",
      },
    ],
    outputs: [{ id: "interpretation", type: "report", description: "Structured radiometric interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest"],
    scientificConstraints: [
      "Does not infer mineralisation, lithology, alteration, or drill targets as fact.",
      "Does not claim G-AID applied height, stripping, or concentration conversion.",
    ],
    supportLevel: "supported",
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "Already-corrected maps and ratios are not geology.",
      "Failed or skipped products must not generate affirmative interpretation language.",
    ],
    expectedArtifacts: ["rad_interpretation.json"],
  }),
  mag({
    id: "gpr.ingest",
    version: "1.0.0",
    title: "GPR ingest",
    description: "Read a documented G-AID GPR 1.0 CSV. Arbitrary GSSI DZT files are not processed.",
    domain: "gpr",
    kernelNodeIds: ["gpr_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "gpr-section",
        adapterIds: ["gpr-csv"],
        required: true,
        description: "Supported GPR-contract catalog records (not an arbitrary .dzt)",
      },
    ],
    outputs: [
      { id: "gpr_canonical", type: "table", description: "Canonical Trace/Sample/Amplitude table", viewer: "table" },
      { id: "gpr_ingest_qc", type: "qc", description: "dt_ns, dx_m, AntennaMHz, Units, CRS", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: ["G-AID GPR 1.0 banner", "Units", "dt_ns", "dx_m", "AntennaMHz", "Trace/Sample/Amplitude"],
    scientificConstraints: [
      "DZT binary headers are not a supported source of dt, dx, or antenna frequency.",
      "Velocity is never assumed from AntennaMHz.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n_traces", "n_samples", "dt_ns", "dx_m", "antenna_mhz", "units"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not identify utilities, voids, archaeology, or lithology."],
    expectedArtifacts: ["gpr_canonical.csv", "gpr_ingest_qc.json"],
  }),
  mag({
    id: "gpr.process",
    version: "1.0.0",
    title: "GPR process",
    description: "Optional dewow, time-zero, SEC t^n gain, and Nyquist-validated Butterworth band-pass (Jol 2009) on a bound G-AID GPR 1.0 section.",
    domain: "gpr",
    kernelNodeIds: ["gpr_process"],
    dependsOn: ["gpr.ingest"],
    inputRoles: [
      {
        role: "gpr-section",
        adapterIds: ["gpr-csv"],
        required: true,
        description: "Canonical GPR samples from gpr.ingest",
      },
    ],
    outputs: [
      { id: "gpr_radargram", type: "table", description: "Processed radargram in two-way time", viewer: "section" },
      { id: "gpr_process_qc", type: "qc", description: "Sampling, Nyquist, dewow window, time-zero, SEC, requested vs applied band-pass", viewer: "json" },
    ],
    parameters: {
      applyDewow: { type: "boolean", required: false, description: "Odd running-mean dewow. Default on. Frozen and recorded.", defaultValue: true },
      dewowWindow: { type: "number", required: false, description: "Odd dewow window length in samples. Default 31.", units: "samples", defaultValue: 31 },
      applyTimeZero: { type: "boolean", required: false, description: "Stack first-break time-zero. Default on.", defaultValue: true },
      timeZeroThreshold: { type: "number", required: false, description: "First-break threshold as a fraction of stack peak. Default 0.05.", units: "fraction", defaultValue: 0.05 },
      applySecGain: { type: "boolean", required: false, description: "SEC t^n gain. Default on (n=2, α=0).", defaultValue: true },
      secPower: { type: "number", required: false, description: "SEC spreading exponent n. Default 2.", defaultValue: 2 },
      secExp: { type: "number", required: false, description: "SEC exponential α. Default 0.", units: "1/s", defaultValue: 0 },
      applyBandpass: { type: "boolean", required: false, description: "Butterworth band-pass. Default on; refused if corners are not Nyquist-safe.", defaultValue: true },
      filterOrder: { type: "number", required: false, description: "Butterworth order. Default 4.", defaultValue: 4 },
      fLowHz: { type: "number", required: false, description: "Band-pass low cut. Default 0.2 × AntennaMHz when Nyquist-safe.", units: "Hz" },
      fHighHz: { type: "number", required: false, description: "Band-pass high cut. Default 2.0 × AntennaMHz when Nyquist-safe; never silently ≥ Nyquist.", units: "Hz" },
    },
    metadataRequirements: ["dt_ns", "dx_m", "AntennaMHz"],
    scientificConstraints: [
      "Sampling frequency and Nyquist are derived from dt_ns. Every requested or default Butterworth corner is validated against Nyquist.",
      "A high-cut at or above Nyquist is refused, not silently clamped to 0.999 × Nyquist.",
      "When the antenna default 0.2–2.0 × AntennaMHz is not Nyquist-safe, a documented safe high-cut of 0.8 × Nyquist is used if the 0.2 × AntennaMHz low-cut still fits; otherwise the filter is skipped and the user must supply fLowHz/fHighHz.",
      "Dewow, time-zero, SEC, and band-pass are optional frozen parameters. A visually enhanced radargram does not have improved geological certainty.",
      "Two-way time is not depth.",
    ],
    supportLevel: "supported",
    qcRequirements: [
      "sampling_hz",
      "nyquist_hz",
      "requested_filter_hz",
      "applied_filter_hz",
      "bandpass_applied",
      "bandpass_adjusted",
      "bandpass_refused",
      "time_zero_sample",
      "dewow_window",
      "sec_power",
      "geological_certainty_improved",
    ],
    viewerTypes: ["section", "json"],
    interpretationLimits: [
      "A processed radargram is not a depth section unless migrated with a user velocity.",
      "A visually enhanced radargram does not have improved geological certainty.",
      "Utilities, voids, archaeology, water table, and rebar are not established.",
    ],
    expectedArtifacts: ["gpr_radargram.csv", "gpr_process_qc.json"],
  }),
  mag({
    id: "gpr.migrate",
    version: "1.0.0",
    title: "GPR Kirchhoff time migration",
    description: "Optional 2-D Kirchhoff time migration (Yilmaz 2001) only when the user supplies a velocity and the documented diffraction benchmark has passed. Off by default.",
    domain: "gpr",
    kernelNodeIds: ["gpr_migrate"],
    dependsOn: ["gpr.process"],
    inputRoles: [
      {
        role: "gpr-section",
        adapterIds: ["gpr-csv"],
        required: true,
        description: "Processed radargram from gpr.process",
      },
    ],
    outputs: [
      { id: "gpr_migrated", type: "table", description: "Migrated radargram; z from user velocity", viewer: "section" },
    ],
    parameters: {
      velocityMs: {
        type: "number",
        required: true,
        description: "Migration velocity. Never assumed from AntennaMHz.",
        units: "m/s",
      },
    },
    metadataRequirements: ["user velocityMs or VelocityMns"],
    scientificConstraints: [
      "Velocity is user-supplied. G-AID does not pick a dielectric constant or 0.1 m/ns default.",
      "Migrated depth is 0.5 v t using that velocity. It is not ground truth.",
      "Migration stays unavailable unless docs/validation/results/gpr_migration_benchmark.json reports all_passed for the noise-free zero-offset diffraction case.",
      "The benchmark is not field data. 3-D, topography, and laterally varying velocity are not implemented.",
    ],
    supportLevel: "supported",
    qcRequirements: ["velocity_ms", "velocity_source", "migrated", "benchmark_passed", "sampling_hz", "nyquist_hz"],
    viewerTypes: ["section", "json"],
    interpretationLimits: [
      "A migrated section is not a measured depth model.",
      "Hyperbola collapse does not prove a pipe, void, or archaeological feature.",
    ],
    expectedArtifacts: ["gpr_migrated.csv", "gpr_migrate_qc.json"],
  }),
  mag({
    id: "gpr.gis",
    version: "1.0.0",
    title: "GPR GIS export",
    description: "Write trace-position GeoJSON when a documented EPSG exists. No silent reprojection.",
    domain: "gpr",
    kernelNodeIds: ["gpr_gis_export"],
    dependsOn: ["gpr.ingest"],
    inputRoles: [
      {
        role: "gpr-section",
        adapterIds: ["gpr-csv"],
        required: true,
        description: "Canonical GPR traces",
      },
    ],
    outputs: [{ id: "gpr_traces", type: "vector", description: "Trace positions GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["EPSG on the GPR contract"],
    scientificConstraints: ["GIS export is skipped without a documented EPSG. Coordinates are not invented."],
    supportLevel: "supported",
    qcRequirements: ["crs_epsg"],
    viewerTypes: ["map", "file"],
    interpretationLimits: ["Trace positions inherit the limits of the radargram product."],
    expectedArtifacts: ["gpr_traces.geojson"],
  }),
  mag({
    id: "gpr.interpret",
    version: "1.0.0",
    title: "GPR interpretation limits",
    description: "Evidence-bound report. Does not confirm utilities, voids, archaeology, water table, or lithology.",
    domain: "gpr",
    kernelNodeIds: ["gpr_interpret"],
    dependsOn: ["gpr.process"],
    inputRoles: [
      {
        role: "gpr-section",
        adapterIds: ["gpr-csv"],
        required: true,
        description: "GPR products already in the run folder",
      },
    ],
    outputs: [{ id: "interpretation", type: "report", description: "Structured GPR interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest/process"],
    scientificConstraints: [
      "Does not infer utilities, voids, archaeology, water table, rebar, or lithology as fact.",
      "A visually enhanced radargram does not have improved geological certainty.",
    ],
    supportLevel: "supported",
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "A radargram is an observation in two-way time (or a user-velocity depth conversion).",
      "Failed or skipped products must not generate affirmative interpretation language.",
    ],
    expectedArtifacts: ["gpr_interpretation.json"],
  }),
  mag({
    id: "borehole.ingest_las",
    version: "1.0.0",
    title: "LAS well-log ingest",
    description: "Read a documented CWLS LAS 2.0 WRAP.NO well log. LASF LiDAR, WRAP.YES, and LAS 3.0 are not processed.",
    domain: "borehole",
    kernelNodeIds: ["las_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "well-log",
        adapterIds: ["las-well"],
        required: true,
        description: "Supported LAS 2.0 WRAP.NO catalog records (not an arbitrary .las or LASF point cloud)",
      },
    ],
    outputs: [
      { id: "borehole_canonical", type: "table", description: "Canonical measured-depth curve table", viewer: "table" },
      { id: "borehole_ingest_qc", type: "qc", description: "VERS, WRAP, WELL, NULL, STRT/STOP/STEP, curves, collar, CRS", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: ["VERS 2.x", "WRAP.NO", "~Well", "~Curve with units", "~ASCII", "depth index DEPT/DEPTH/MD"],
    scientificConstraints: [
      "LASF / LAZ point clouds are not well logs.",
      "WRAP.YES is not unwrapped. LAS 3.0 is not ingested.",
      "Unknown mnemonics remain unknown. Curve meaning is never invented from the mnemonic.",
      "Measured depth is not true vertical depth.",
    ],
    supportLevel: "supported",
    qcRequirements: ["las_version", "wrap", "depth_index", "null_value", "curves", "trajectory_computed"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not identify lithology, aquifers, mineralisation, water, ore, or reservoir."],
    expectedArtifacts: ["borehole_canonical.csv", "borehole_ingest_qc.json"],
  }),
  mag({
    id: "borehole.view_logs",
    version: "1.0.0",
    title: "Borehole log viewer metadata",
    description: "Build multi-track measured-depth viewer data: depth scale, units, null gaps, selectable curves, and provenance.",
    domain: "borehole",
    kernelNodeIds: ["borehole_view"],
    dependsOn: ["borehole.ingest_las"],
    inputRoles: [
      {
        role: "well-log",
        adapterIds: ["las-well"],
        required: true,
        description: "Canonical log from borehole.ingest_las",
      },
    ],
    outputs: [{ id: "borehole_tracks", type: "table", description: "Multi-track measured-depth log", viewer: "log" }],
    parameters: {
      selectedCurves: {
        type: "string",
        required: false,
        description: "Optional comma-separated curve mnemonics to display. Default is all non-depth curves.",
      },
    },
    metadataRequirements: ["depth index", "curve units", "null value"],
    scientificConstraints: [
      "The depth axis is measured depth, increasing down the hole. It is not TVD or a map trajectory.",
      "Null samples are gaps, not interpolated geology.",
    ],
    supportLevel: "supported",
    qcRequirements: ["depth_reference", "selected_curves", "trajectory_computed"],
    viewerTypes: ["log", "json"],
    interpretationLimits: ["A log display is not a lithology column or a 3-D well path."],
    expectedArtifacts: ["borehole_tracks.json", "borehole_tracks.meta.json"],
  }),
  mag({
    id: "borehole.map_collar",
    version: "1.0.0",
    title: "Borehole collar map",
    description: "Write a collar GeoJSON only when coordinates and a documented or explicitly user-confirmed CRS exist.",
    domain: "borehole",
    kernelNodeIds: ["borehole_map_collar"],
    dependsOn: ["borehole.ingest_las"],
    inputRoles: [
      {
        role: "well-log",
        adapterIds: ["las-well"],
        required: true,
        description: "Canonical log with optional collar coordinates",
      },
    ],
    outputs: [{ id: "borehole_collar", type: "vector", description: "Collar point GeoJSON", viewer: "map" }],
    parameters: {
      collarCrsConfirmed: {
        type: "boolean",
        required: false,
        description: "User confirms geographic collar coordinates as EPSG:4326 when the LAS file has LATI/LONG but no EPSG.",
        defaultValue: false,
      },
    },
    metadataRequirements: ["collar X/Y or LATI/LONG", "EPSG or collarCrsConfirmed"],
    scientificConstraints: [
      "A collar is not mapped without coordinates and CRS. Vertical logs remain viewable.",
      "Geographic vs easting-northing is distinguished. Elevation is a datum, not a trajectory.",
      "Deviation surveys are not converted into well paths.",
    ],
    supportLevel: "supported",
    qcRequirements: ["crs_epsg", "coordinate_kind", "location_quality", "collar_mapped", "trajectory_computed"],
    viewerTypes: ["map", "json"],
    interpretationLimits: ["A collar point is not a well path. Overlapping geophysical layers are coincidence, not a joint proof."],
    expectedArtifacts: ["borehole_collar.geojson", "borehole_collar.meta.json", "borehole_collar_qc.json"],
  }),
  mag({
    id: "borehole.interpret",
    version: "1.0.0",
    title: "Borehole interpretation limits",
    description: "Evidence-bound report. Does not classify lithology, aquifers, mineralisation, resources, or drill targets.",
    domain: "borehole",
    kernelNodeIds: ["borehole_interpret"],
    dependsOn: ["borehole.view_logs"],
    inputRoles: [
      {
        role: "well-log",
        adapterIds: ["las-well"],
        required: true,
        description: "Borehole products already in the run folder",
      },
    ],
    outputs: [{ id: "interpretation", type: "report", description: "Structured borehole interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest/view"],
    scientificConstraints: [
      "Does not infer lithology, aquifers, mineralisation, water, ore, reservoir, correlations, resources, or drill targets as fact.",
      "GR, resistivity, density, gamma, and sonic remain observed curves with unknown semantics unless the user supplied meaning.",
    ],
    supportLevel: "supported",
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "A log is an observation at measured depth.",
      "Failed or skipped collar mapping must not generate a fabricated well location.",
    ],
    expectedArtifacts: ["borehole_interpretation.json"],
  }),
  mag({
    id: "gis.vector_ingest",
    version: "1.0.0",
    title: "GIS vector ingest",
    description:
      "Parse RFC 7946 GeoJSON (OGC:CRS84), legacy-GeoJSON with a validated CRS mapping, or a G-AID custom import into a canonical vector catalog. Shapefile and GeoPackage remain recognised-unsupported.",
    domain: "gis",
    kernelNodeIds: ["vector_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "gis-vector",
        adapterIds: ["geojson"],
        required: true,
        description: "Supported GeoJSON catalog records (RFC 7946 OGC:CRS84, legacy-GeoJSON, or G-AID custom import)",
      },
    ],
    outputs: [
      { id: "vector_canonical", type: "vector", description: "Canonical vector catalog", viewer: "json" },
      { id: "vector_ingest_qc", type: "qc", description: "CRS, geometry types, attributes, roles, provenance", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: ["documented CRS (OGC:CRS84 or EPSG)", "valid Point/Line/Polygon geometries"],
    scientificConstraints: [
      "Shapefile sidecars and GeoPackage are flagged, not parsed.",
      "Filename geology/tenure/fault labels are not assigned as layer roles.",
      "RFC 7946 GeoJSON with no crs member is OGC:CRS84. It is not EPSG:4326.",
      "Legacy crs members and companion .prj / EPSG= comments are not RFC 7946.",
      "G-AID will not silently reproject or swap axes.",
    ],
    supportLevel: "supported",
    qcRequirements: ["crs_epsg", "geometry_types", "attribute_names", "role", "role_reviewed", "reprojected"],
    viewerTypes: ["json", "map"],
    interpretationLimits: ["Ingest does not identify geology, mineralisation, tenure validity, or alteration as fact."],
    expectedArtifacts: ["vector_canonical.json", "vector_ingest_qc.json"],
  }),
  mag({
    id: "gis.vector_view",
    version: "1.0.0",
    title: "GIS vector view",
    description:
      "Map source points, lines, and polygons with attributes, legend, visibility, opacity, CRS status, and provenance. No geoprocessing.",
    domain: "gis",
    kernelNodeIds: ["vector_view"],
    dependsOn: ["gis.vector_ingest"],
    inputRoles: [
      {
        role: "gis-vector",
        adapterIds: ["geojson"],
        required: true,
        description: "Canonical vectors from gis.vector_ingest",
      },
    ],
    outputs: [{ id: "vector_tracks", type: "vector", description: "Source geometry viewer metadata", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["canonical vector catalog"],
    scientificConstraints: [
      "View is source geometry in the documented CRS. Attributes keep unknown semantics.",
      "Spatial overlap is not geological proof.",
    ],
    supportLevel: "supported",
    qcRequirements: ["crs_required_for_overlay", "silent_reprojection", "role_inferred_from_filename"],
    viewerTypes: ["map", "json"],
    interpretationLimits: ["A displayed geology polygon or fault line remains source information, not an AI interpretation."],
    expectedArtifacts: ["vector_tracks.json", "vector_tracks.meta.json"],
  }),
  mag({
    id: "gis.spatial_overlap",
    version: "1.0.0",
    title: "Spatial overlap table",
    description:
      "Reproducible geometric overlap table for same-CRS valid layers. Coincidence is not a geological, mineral, or causal relationship.",
    domain: "gis",
    kernelNodeIds: ["vector_overlap"],
    dependsOn: ["gis.vector_ingest"],
    inputRoles: [
      {
        role: "gis-vector",
        adapterIds: ["geojson"],
        required: true,
        description: "At least two same-CRS supported GeoJSON layers",
      },
    ],
    outputs: [{ id: "vector_overlap", type: "table", description: "Geometric overlap rows", viewer: "table" }],
    parameters: {},
    metadataRequirements: ["two documented same-CRS layers"],
    scientificConstraints: [
      "No buffer, clip, dissolve, or silent reprojection.",
      "Overlap does not generate mineral targets or drill recommendations.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n_rows", "blocked", "reprojected", "geological_certainty_improved"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Overlap is a geometric table, not a prospectivity map."],
    expectedArtifacts: ["vector_overlap.csv", "vector_overlap.json", "vector_overlap_qc.json"],
  }),
  mag({
    id: "gis.export_vector",
    version: "1.0.0",
    title: "GIS vector export",
    description: "Write documented GeoJSON copies with CRS, geometry types, attributes, and provenance. Not shapefile or GeoPackage.",
    domain: "gis",
    kernelNodeIds: ["vector_export"],
    dependsOn: ["gis.vector_ingest"],
    inputRoles: [
      {
        role: "gis-vector",
        adapterIds: ["geojson"],
        required: true,
        description: "Canonical vectors from gis.vector_ingest",
      },
    ],
    outputs: [{ id: "vector_export", type: "vector", description: "Exported GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["canonical vector catalog"],
    scientificConstraints: ["Export is GeoJSON only. No shapefile, GeoPackage, KML, or FileGDB writers."],
    supportLevel: "supported",
    qcRequirements: ["format", "shapefile", "geopackage", "reprojected", "attribute_editing"],
    viewerTypes: ["json"],
    interpretationLimits: ["Export copies source geometry. It does not edit attributes or reproject."],
    expectedArtifacts: ["vector_export_1.geojson", "vector_export.meta.json"],
  }),
  mag({
    id: "gis.interpret",
    version: "1.0.0",
    title: "GIS interpretation notes",
    description:
      "Evidence-bound notes on catalogued vector layers. Faults, geology polygons, tenure, alteration, and samples remain source information.",
    domain: "gis",
    kernelNodeIds: ["vector_interpret"],
    dependsOn: ["gis.vector_view"],
    inputRoles: [
      {
        role: "gis-vector",
        adapterIds: ["geojson"],
        required: true,
        description: "Vector products already in the run folder",
      },
    ],
    outputs: [{ id: "interpretation", type: "report", description: "Structured GIS interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest/view"],
    scientificConstraints: [
      "Does not generate mineral targets, prospectivity maps, resource/reserve claims, or drill recommendations from overlays.",
      "User-assigned roles are catalog labels, not geological confirmation.",
    ],
    supportLevel: "supported",
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "Observed vectors are source layers.",
      "Failed overlap must not generate a fabricated spatial relationship.",
    ],
    expectedArtifacts: ["vector_interpretation.json"],
  }),
  mag({
    id: "geochem.ingest",
    version: "1.0.0",
    title: "Geochemistry ingest",
    description:
      "Read a documented G-AID GEOCHEM 1.0 assay/sample CSV or XYZ. Arbitrary CSVs with Fe/Cu/Au columns are not geochemistry.",
    domain: "geochemistry",
    kernelNodeIds: ["geochem_ingest"],
    dependsOn: [],
    inputRoles: [
      {
        role: "geochem-samples",
        adapterIds: ["geochem-csv", "geochem-xyz"],
        required: true,
        description: "Supported GEOCHEM-contract catalog records (not an arbitrary chemistry CSV)",
      },
    ],
    outputs: [
      { id: "geochem_canonical", type: "table", description: "Canonical assay table with censored flags", viewer: "table" },
      { id: "geochem_ingest_qc", type: "qc", description: "CRS, medium, units, mapping, BDL treatment", viewer: "json" },
    ],
    parameters: {},
    metadataRequirements: ["SampleID", "X", "Y", "documented CRS", "sample medium", "element columns with units"],
    scientificConstraints: [
      "Element-like column names are not geochemistry.",
      "Below-detection values are censored. They are never replaced with zero, imputed, or silently log-transformed.",
      "Noncanonical headers need a reviewed mapping.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n", "crs", "medium", "units", "replaced_bdl_with_zero: false"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["Ingest does not identify ore, mineralisation, or drill targets."],
    expectedArtifacts: ["geochem_canonical.csv", "geochem_canonical.json", "geochem_ingest_qc.json", "geochem_mapping.json"],
  }),
  mag({
    id: "geochem.qc",
    version: "1.0.0",
    title: "Geochemistry QC",
    description:
      "Validate coordinates, duplicate IDs/locations, mixed units, detection limits, qualifiers, and missing metadata. QA/QC summaries for blanks/standards/duplicates only when those records and rules are explicit.",
    domain: "geochemistry",
    kernelNodeIds: ["geochem_qc"],
    dependsOn: ["geochem.ingest"],
    inputRoles: [
      {
        role: "geochem-samples",
        adapterIds: ["geochem-csv", "geochem-xyz"],
        required: true,
        description: "Canonical samples from geochem.ingest",
      },
    ],
    outputs: [{ id: "geochem_qc", type: "qc", description: "QC report distinguishing raw vs derived vs display-only", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["canonical assay table"],
    scientificConstraints: [
      "Blanks, standards, and duplicates are summarised only when QCFlag records and expected-value rules are present.",
      "Censored values stay censored.",
    ],
    supportLevel: "supported",
    qcRequirements: ["duplicate_sample_ids", "duplicate_locations", "mixed_units", "n_censored", "qa_qc.applied"],
    viewerTypes: ["json"],
    interpretationLimits: ["QC flags are observations about the table, not mineralisation proof."],
    expectedArtifacts: ["geochem_qc.json"],
  }),
  mag({
    id: "geochem.map_points",
    version: "1.0.0",
    title: "Geochemistry sample map",
    description:
      "Map sample points with element, unit, qualifier, source, and filter state. Blocked without a documented CRS.",
    domain: "geochemistry",
    kernelNodeIds: ["geochem_map_points"],
    dependsOn: ["geochem.ingest"],
    inputRoles: [
      {
        role: "geochem-samples",
        adapterIds: ["geochem-csv", "geochem-xyz"],
        required: true,
        description: "Canonical samples with documented CRS",
      },
    ],
    outputs: [{ id: "geochem_points", type: "vector", description: "Sample-point GeoJSON", viewer: "map" }],
    parameters: {},
    metadataRequirements: ["documented CRS", "X/Y"],
    scientificConstraints: [
      "Points are not mapped without CRS. Unknown/mixed units stay visible and block comparison.",
      "Visual scale is raw observation, not an anomaly score.",
    ],
    supportLevel: "supported",
    qcRequirements: ["crs", "n_features", "visual_scale"],
    viewerTypes: ["map", "json"],
    interpretationLimits: ["A sample point is an observation location. Overlay with geology or geophysics is coincidence."],
    expectedArtifacts: ["geochem_points.geojson", "geochem_points.meta.json"],
  }),
  mag({
    id: "geochem.summary",
    version: "1.0.0",
    title: "Geochemistry summary",
    description:
      "Per-element counts and uncensored min/max/median. Mixed or unknown units block direct comparison.",
    domain: "geochemistry",
    kernelNodeIds: ["geochem_summary"],
    dependsOn: ["geochem.qc"],
    inputRoles: [
      {
        role: "geochem-samples",
        adapterIds: ["geochem-csv", "geochem-xyz"],
        required: true,
        description: "Canonical samples from geochem.ingest",
      },
    ],
    outputs: [{ id: "geochem_summary", type: "qc", description: "Summary statistics of uncensored values", viewer: "json" }],
    parameters: {
      elements: {
        type: "string",
        required: false,
        description: "Optional comma-separated element keys to select/compare. Mixed units block comparison.",
      },
    },
    metadataRequirements: ["canonical assay table"],
    scientificConstraints: [
      "Statistics exclude censored below-detection values. They are not treated as zero.",
      "Unknown or mixed units block direct comparison.",
    ],
    supportLevel: "supported",
    qcRequirements: ["n", "n_censored", "comparisons.blocked"],
    viewerTypes: ["json"],
    interpretationLimits: ["A high uncensored maximum is an observation, not economic grade."],
    expectedArtifacts: ["geochem_summary.json"],
  }),
  mag({
    id: "geochem.display_transform",
    version: "1.0.0",
    title: "Geochemistry display transform",
    description:
      "Optional log10 of strictly positive uncensored values, only when explicitly user-approved. Originals are preserved. Off by default.",
    domain: "geochemistry",
    kernelNodeIds: ["geochem_display_transform"],
    dependsOn: ["geochem.qc"],
    inputRoles: [
      {
        role: "geochem-samples",
        adapterIds: ["geochem-csv", "geochem-xyz"],
        required: true,
        description: "Canonical raw assays; transform is display-only",
      },
    ],
    outputs: [{ id: "geochem_display", type: "table", description: "Display-only transform table", viewer: "table" }],
    parameters: {
      displayTransform: {
        type: "string",
        required: true,
        description: "Only log10 is implemented. Mixed units, zeros, negatives, and censored values are skipped.",
      },
      approved: {
        type: "boolean",
        required: true,
        description: "User approval. The transform does not run without this flag.",
        defaultValue: false,
      },
      element: {
        type: "string",
        required: false,
        description: "Optional element key. Default is all strictly positive uncensored columns.",
      },
    },
    metadataRequirements: ["user approval", "strictly positive uncensored values"],
    scientificConstraints: [
      "Not a default chat capability.",
      "Does not overwrite canonical values.",
      "Does not impute BDL or log-transform zeros/negatives.",
    ],
    supportLevel: "supported",
    qcRequirements: ["approved", "originals_preserved", "kind: display-only"],
    viewerTypes: ["table", "json"],
    interpretationLimits: ["A log colour stretch is display-only. Geological certainty is not improved."],
    expectedArtifacts: ["geochem_display.csv", "geochem_display.meta.json"],
  }),
  mag({
    id: "geochem.interpret",
    version: "1.0.0",
    title: "Geochemistry interpretation limits",
    description:
      "Evidence-bound report. High values are observations, not ore, economic grade, mineralisation, or drill targets.",
    domain: "geochemistry",
    kernelNodeIds: ["geochem_interpret"],
    dependsOn: ["geochem.summary"],
    inputRoles: [
      {
        role: "geochem-samples",
        adapterIds: ["geochem-csv", "geochem-xyz"],
        required: true,
        description: "Geochemistry products already in the run folder",
      },
    ],
    outputs: [{ id: "interpretation", type: "report", description: "Structured geochemistry interpretation limits", viewer: "json" }],
    parameters: {},
    metadataRequirements: ["QC JSON from ingest/qc/summary"],
    scientificConstraints: [
      "Does not infer ore, economic grade, mineralisation, or drill targets as fact.",
      "Spatial association with other layers is not causal evidence.",
    ],
    supportLevel: "supported",
    qcRequirements: ["observations vs assumptions listed"],
    viewerTypes: ["json"],
    interpretationLimits: [
      "High assay values are observations.",
      "Failed or skipped mapping must not generate fabricated sample locations.",
    ],
    expectedArtifacts: ["geochem_interpretation.json"],
  }),
];

const BY_ID = new Map(CAPABILITIES.map((capability) => [capability.id, capability]));

export function listCapabilities(): ScientificCapability[] {
  return CAPABILITIES.slice();
}

export function getCapability(id: string): ScientificCapability | undefined {
  return BY_ID.get(id as UserCapabilityId);
}

export function isRegisteredCapability(id: string): id is UserCapabilityId {
  return BY_ID.has(id as UserCapabilityId);
}

export function capabilityVersionMap(): Record<string, string> {
  const versions: Record<string, string> = {};
  for (const capability of CAPABILITIES) versions[capability.id] = capability.version;
  return versions;
}

export { USER_CAPABILITY_IDS };
